// Periodic-table discovery recipes.
//
// Conceptual recipes associate an element with a real source, property, or use;
// they do not claim that ordinary mixing creates the element. Physical,
// chemical, and industrial recipes describe real processes in simplified game
// form. Nuclear recipes omit isotope numbers from their inputs, so their
// explanations name the relevant process or representative isotopes.
export const periodicRecipes = [
  { a: 'proton', b: 'electron', result: 'element_h', type: 'physical', explanation: 'A proton bound to an electron is a neutral hydrogen atom.' },
  { a: 'element_h', b: 'fusion', result: 'element_he', type: 'physical', explanation: 'Stars fuse hydrogen nuclei into helium; the game compresses the multistep stellar reaction.' },
  { a: 'battery', b: 'chemistry', result: 'element_li', type: 'conceptual', explanation: 'Lithium is strongly associated with rechargeable battery chemistry; this is a use association, not extraction.' },
  { a: 'emerald_g', b: 'chemistry', result: 'element_be', type: 'conceptual', explanation: 'Emerald is a variety of beryl, a mineral whose crystal structure contains beryllium.' },
  { a: 'glass', b: 'chemistry', result: 'element_b', type: 'conceptual', explanation: 'Boron compounds are key ingredients in heat-resistant borosilicate glass; this is a materials association.' },
  { a: 'carbon', b: 'chemistry', result: 'element_c', type: 'conceptual', explanation: 'This bridges the general Carbon discovery to its periodic-table entry; both represent the same element.' },
  { a: 'air', b: 'distill', result: 'element_n', type: 'industrial', explanation: 'Industrial nitrogen is separated by liquefying air and fractionally distilling it.' },
  { a: 'oxygen', b: 'chemistry', result: 'element_o', type: 'conceptual', explanation: 'This bridges the general Oxygen discovery to its periodic-table entry; both represent the same element.' },
  { a: 'acid', b: 'electrolysis', result: 'element_f', type: 'chemical', explanation: 'Elemental fluorine is produced by electrolysing anhydrous hydrogen fluoride mixtures; Acid abstracts that feedstock.' },
  { a: 'gas', b: 'light', result: 'element_ne', type: 'conceptual', explanation: 'Excited neon gas produces the characteristic glow of neon lighting; this is a property association.' },
  { a: 'salt', b: 'electrolysis', result: 'element_na', type: 'chemical', explanation: 'Electrolysis of molten sodium chloride produces sodium metal; the game omits the molten-cell details.' },
  { a: 'ocean', b: 'electrolysis', result: 'element_mg', type: 'industrial', explanation: 'Magnesium can be recovered from seawater-derived salts and then produced by electrolysis; the stages are compressed.' },
  { a: 'ore', b: 'electricity', result: 'element_al', type: 'industrial', explanation: 'Aluminium is made by electrolytic reduction of alumina refined from bauxite ore; Electricity represents the Hall-Heroult process.' },
  { a: 'silicon', b: 'chemistry', result: 'element_si', type: 'conceptual', explanation: 'This bridges the general Silicon discovery to its periodic-table entry; both represent the same element.' },
  { a: 'bone', b: 'chemistry', result: 'element_p', type: 'conceptual', explanation: 'Bones contain calcium phosphate, a real phosphorus reservoir; this is a source association rather than direct extraction.' },
  { a: 'sulfur', b: 'chemistry', result: 'element_s', type: 'conceptual', explanation: 'This bridges the general Sulfur discovery to its periodic-table entry; both represent the same element.' },
  { a: 'salt', b: 'electricity', result: 'element_cl', type: 'chemical', explanation: 'The chlor-alkali process uses electricity to electrolyse brine and produce chlorine; the equipment is abstracted.' },
  { a: 'air', b: 'element_n', result: 'element_ar', type: 'industrial', explanation: 'After nitrogen is separated from air, further fractional distillation can isolate argon from the remaining gases.' },
  { a: 'ash', b: 'chemistry', result: 'element_k', type: 'conceptual', explanation: 'Potassium takes its name from potash, historically obtained from plant ashes; this is a source association.' },
  { a: 'bone', b: 'mineral', result: 'element_ca', type: 'conceptual', explanation: 'Bone mineral is rich in calcium phosphate; this is a composition association, not a route to calcium metal.' },
  { a: 'lamp', b: 'mineral', result: 'element_sc', type: 'conceptual', explanation: 'Scandium occurs in rare minerals and scandium iodide is used in high-intensity lamps; this links source and use.' },
  { a: 'ore', b: 'strength', result: 'element_ti', type: 'conceptual', explanation: 'Titanium is extracted from ores and valued for high strength at low weight; this is a source-property association.' },
  { a: 'steel', b: 'chemistry', result: 'element_v', type: 'conceptual', explanation: 'Vanadium is an important steel-alloy additive; this is a metallurgical association rather than elemental production.' },
  { a: 'metal', b: 'color', result: 'element_cr', type: 'conceptual', explanation: 'Chromium is a metal whose many vividly colored compounds inspired its name; this is a property association.' },
  { a: 'steel', b: 'battery', result: 'element_mn', type: 'conceptual', explanation: 'Manganese is important in both steelmaking and battery cathodes; the recipe links two real uses.' },
  { a: 'iron', b: 'chemistry', result: 'element_fe', type: 'conceptual', explanation: 'This bridges the general Iron discovery to its periodic-table entry; both represent the same element.' },
  { a: 'magnet', b: 'blue', result: 'element_co', type: 'conceptual', explanation: 'Cobalt is ferromagnetic and cobalt compounds make famous blue pigments; this links two real properties.' },
  { a: 'battery', b: 'magnet', result: 'element_ni', type: 'conceptual', explanation: 'Nickel is ferromagnetic and widely used in rechargeable batteries; this is a property-use association.' },
  { a: 'copper', b: 'chemistry', result: 'element_cu', type: 'conceptual', explanation: 'This bridges the general Copper discovery to its periodic-table entry; both represent the same element.' },
  { a: 'battery', b: 'metal', result: 'element_zn', type: 'conceptual', explanation: 'Zinc is a metal used in batteries and galvanizing; this is a use association, not a production reaction.' },
  { a: 'semiconductor', b: 'liquid', result: 'element_ga', type: 'conceptual', explanation: 'Gallium is used in semiconductors and melts just above room temperature; this links use and physical property.' },
  { a: 'semiconductor', b: 'glass', result: 'element_ge', type: 'conceptual', explanation: 'Germanium is used in semiconductors and infrared optical glass; this is a technology association.' },
  { a: 'element_ga', b: 'semiconductor', result: 'element_as', type: 'conceptual', explanation: 'Gallium arsenide is a major compound semiconductor; this identifies arsenic through a real material partnership.' },
  { a: 'photography', b: 'chemistry', result: 'element_se', type: 'conceptual', explanation: 'Selenium photoconductivity supported early imaging and photocopying technologies; this is a historical use association.' },
  { a: 'photography', b: 'salt', result: 'element_br', type: 'conceptual', explanation: 'Light-sensitive silver bromide salts underpin film photography; this is a compound-use association.' },
  { a: 'camera', b: 'gas', result: 'element_kr', type: 'conceptual', explanation: 'Krypton gas has been used in bright photographic flash lamps; this is a technology association.' },
  { a: 'clock', b: 'mineral', result: 'element_rb', type: 'conceptual', explanation: 'Rubidium occurs in minerals and its atomic transitions are used in frequency standards; this links source and use.' },
  { a: 'fire', b: 'red', result: 'element_sr', type: 'conceptual', explanation: 'Strontium salts color flames bright red, which is why they are used in signal flares and fireworks.' },
  { a: 'light', b: 'metal', result: 'element_y', type: 'conceptual', explanation: 'Yttrium compounds are used in phosphors, LEDs, and YAG lasers; this is an optical-material association.' },
  { a: 'ceramic', b: 'metal', result: 'element_zr', type: 'conceptual', explanation: 'Zirconium forms both useful metals and zirconia ceramics; this is a materials association.' },
  { a: 'steel', b: 'magnetism', result: 'element_nb', type: 'conceptual', explanation: 'Niobium strengthens alloys and forms superconductors used in powerful magnets; this links real applications.' },
  { a: 'steel', b: 'tool', result: 'element_mo', type: 'conceptual', explanation: 'Molybdenum is added to high-strength tool steels; this is a metallurgical use association.' },
  { a: 'element_mo', b: 'reactor', result: 'element_tc', type: 'physical', explanation: 'Technetium-99m is obtained from molybdenum-99 produced in reactors; the isotope and decay steps are compressed.' },
  { a: 'chemistry', b: 'electronics', result: 'element_ru', type: 'conceptual', explanation: 'Ruthenium is used in catalysts and durable electrical contacts; this links two real uses.' },
  { a: 'car', b: 'chemistry', result: 'element_rh', type: 'conceptual', explanation: 'Rhodium catalyses exhaust reactions in automotive catalytic converters; this is a use association.' },
  { a: 'car', b: 'element_h', result: 'element_pd', type: 'conceptual', explanation: 'Palladium is used in catalytic converters and readily absorbs hydrogen; this links two real properties.' },
  { a: 'silver', b: 'chemistry', result: 'element_ag', type: 'conceptual', explanation: 'This bridges the general Silver discovery to its periodic-table entry; both represent the same element.' },
  { a: 'battery', b: 'yellow', result: 'element_cd', type: 'conceptual', explanation: 'Cadmium is associated with nickel-cadmium batteries and cadmium-yellow pigments; this links two historical uses.' },
  { a: 'touchscreen', b: 'metal', result: 'element_in', type: 'conceptual', explanation: 'Indium tin oxide is the transparent conductor used by many touchscreens; this is a technology association.' },
  { a: 'tin', b: 'chemistry', result: 'element_sn', type: 'conceptual', explanation: 'This bridges the general Tin discovery to its periodic-table entry; both represent the same element.' },
  { a: 'chemical', b: 'metal', result: 'element_sb', type: 'conceptual', explanation: 'Antimony is a metalloid used in alloys and flame-retardant compounds; this is a material association.' },
  { a: 'element_cd', b: 'solar_cell', result: 'element_te', type: 'conceptual', explanation: 'Cadmium telluride is a commercial photovoltaic material; this identifies tellurium through a real compound use.' },
  { a: 'medicine', b: 'salt', result: 'element_i', type: 'conceptual', explanation: 'Iodide is added to salt for thyroid health and iodine compounds have medical uses; this is a use association.' },
  { a: 'gas', b: 'lamp', result: 'element_xe', type: 'conceptual', explanation: 'Xenon gas is used in high-intensity discharge and flash lamps; this is a technology association.' },
  { a: 'clock', b: 'chemistry', result: 'element_cs', type: 'conceptual', explanation: 'The caesium-133 transition defines the SI second; this is an atomic-clock association.' },
  { a: 'hospital', b: 'mineral', result: 'element_ba', type: 'conceptual', explanation: 'Barium occurs in barite, and insoluble barium sulfate is used as an X-ray contrast agent; this links source and use.' },
  { a: 'camera', b: 'glass', result: 'element_la', type: 'conceptual', explanation: 'Lanthanum compounds improve high-index optical glass used in camera lenses; this is a technology association.' },
  { a: 'glass', b: 'metal', result: 'element_ce', type: 'conceptual', explanation: 'Cerium oxide is used to polish glass, while cerium itself is a metal; this links real material roles.' },
  { a: 'glass', b: 'green', result: 'element_pr', type: 'conceptual', explanation: 'Praseodymium compounds color glass yellow-green; this is an optical-material association.' },
  { a: 'magnet', b: 'metal', result: 'element_nd', type: 'conceptual', explanation: 'Neodymium metal is central to exceptionally strong permanent magnets; this is a use association.' },
  { a: 'element_nd', b: 'reactor', result: 'element_pm', type: 'physical', explanation: 'Promethium can be made by neutron activation of neodymium followed by beta decay; isotope steps are compressed.' },
  { a: 'element_co', b: 'magnet', result: 'element_sm', type: 'conceptual', explanation: 'Samarium-cobalt alloys make heat-resistant permanent magnets; this identifies samarium through a real alloy.' },
  { a: 'screen', b: 'red', result: 'element_eu', type: 'conceptual', explanation: 'Europium compounds provide red phosphors in display screens; this is a technology association.' },
  { a: 'medicine', b: 'magnetism', result: 'element_gd', type: 'conceptual', explanation: 'Gadolinium compounds are used as MRI contrast agents because of strong paramagnetism; this is a medical association.' },
  { a: 'screen', b: 'green', result: 'element_tb', type: 'conceptual', explanation: 'Terbium compounds provide green phosphors in displays and lamps; this is a technology association.' },
  { a: 'magnet', b: 'heat', result: 'element_dy', type: 'conceptual', explanation: 'Dysprosium helps permanent magnets retain performance at high temperatures; this is a materials association.' },
  { a: 'light', b: 'magnetism', result: 'element_ho', type: 'conceptual', explanation: 'Holmium has an exceptionally large magnetic moment and is used in lasers; this links two real properties.' },
  { a: 'glass', b: 'internet', result: 'element_er', type: 'conceptual', explanation: 'Erbium-doped glass amplifies signals in fiber-optic communications; this is a technology association.' },
  { a: 'medicine', b: 'light', result: 'element_tm', type: 'conceptual', explanation: 'Thulium lasers are used for selected medical procedures; this is a medical-technology association.' },
  { a: 'glass', b: 'signal', result: 'element_yb', type: 'conceptual', explanation: 'Ytterbium-doped fibers amplify optical signals and power fiber lasers; this is a technology association.' },
  { a: 'camera', b: 'medicine', result: 'element_lu', type: 'conceptual', explanation: 'Lutetium-based scintillator crystals detect radiation in PET medical imaging; this is a detector association.' },
  { a: 'reactor', b: 'metal', result: 'element_hf', type: 'conceptual', explanation: 'Hafnium metal absorbs neutrons and is used in reactor control rods; this is a nuclear-engineering association.' },
  { a: 'electronics', b: 'metal', result: 'element_ta', type: 'conceptual', explanation: 'Tantalum metal is widely used in compact electronic capacitors; this is a technology association.' },
  { a: 'bulb', b: 'metal', result: 'element_w', type: 'conceptual', explanation: 'Tungsten metal was the classic incandescent-bulb filament because of its very high melting point.' },
  { a: 'rocket_engine', b: 'metal', result: 'element_re', type: 'conceptual', explanation: 'Rhenium-containing superalloys withstand extreme temperatures in rocket and turbine engines; this is a use association.' },
  { a: 'mass', b: 'metal', result: 'element_os', type: 'conceptual', explanation: 'Osmium is a metal with one of the highest measured densities; Mass represents that defining property.' },
  { a: 'meteor', b: 'metal', result: 'element_ir', type: 'conceptual', explanation: 'An iridium-rich layer is evidence for the asteroid impact at the end of the Cretaceous; this is a geochemical association.' },
  { a: 'car', b: 'metal', result: 'element_pt', type: 'conceptual', explanation: 'Platinum metal catalyses exhaust reactions in vehicle catalytic converters; this is a use association.' },
  { a: 'gold', b: 'chemistry', result: 'element_au', type: 'conceptual', explanation: 'This bridges the general Gold discovery to its periodic-table entry; both represent the same element.' },
  { a: 'liquid', b: 'metal', result: 'element_hg', type: 'conceptual', explanation: 'Mercury is the only metallic element liquid under ordinary room conditions; this is a classification association.' },
  { a: 'electronics', b: 'medicine', result: 'element_tl', type: 'conceptual', explanation: 'Thallium compounds have been used in electronic detectors and nuclear-medicine imaging; this is a use association.' },
  { a: 'battery', b: 'weight', result: 'element_pb', type: 'conceptual', explanation: 'Lead is a dense metal central to lead-acid batteries; this links a major use with a physical property.' },
  { a: 'medicine', b: 'metal', result: 'element_bi', type: 'conceptual', explanation: 'Bismuth is a metal whose compounds are used in medicines; this is a use association.' },
  { a: 'element_bi', b: 'reactor', result: 'element_po', type: 'physical', explanation: 'Polonium-210 can be made by neutron capture in bismuth-209 followed by beta decay; the decay step is compressed.' },
  { a: 'element_bi', b: 'element_he', result: 'element_at', type: 'physical', explanation: 'Astatine was first made by bombarding bismuth-209 with alpha particles, represented here by helium nuclei.' },
  { a: 'element_ra', b: 'decay', result: 'element_rn', type: 'physical', explanation: 'Radon is produced in the alpha decay of radium isotopes.' },
  { a: 'element_ac', b: 'decay', result: 'element_fr', type: 'physical', explanation: 'Francium-223 occurs as a rare alpha-decay branch of actinium-227.' },
  { a: 'element_u', b: 'decay', result: 'element_ra', type: 'physical', explanation: 'Radium occurs in uranium decay series; the many intermediate nuclides are compressed into one discovery step.' },
  { a: 'element_ra', b: 'reactor', result: 'element_ac', type: 'physical', explanation: 'Actinium-227 can be produced by neutron capture in radium-226 followed by beta decay; isotope steps are compressed.' },
  { a: 'mineral', b: 'nuclear', result: 'element_th', type: 'conceptual', explanation: 'Thorium is a naturally occurring radioactive metal found in minerals and studied as a fertile nuclear material.' },
  { a: 'element_th', b: 'reactor', result: 'element_pa', type: 'physical', explanation: 'Neutron capture in thorium-232 followed by beta decay produces protactinium-233; the stages are compressed.' },
  { a: 'uranium', b: 'chemistry', result: 'element_u', type: 'conceptual', explanation: 'This bridges the general Uranium discovery to its periodic-table entry; both represent the same element.' },
  { a: 'element_u', b: 'reactor', result: 'element_np', type: 'physical', explanation: 'Neutron capture in uranium-238 followed by beta decay produces neptunium-239; isotope steps are compressed.' },
  { a: 'element_np', b: 'reactor', result: 'element_pu', type: 'physical', explanation: 'Neptunium-239 beta-decays to plutonium-239 after uranium irradiation; Reactor represents the production chain.' },
  { a: 'element_pu', b: 'reactor', result: 'element_am', type: 'physical', explanation: 'Americium is produced through successive neutron captures and beta decay starting from plutonium; the chain is compressed.' },
  { a: 'element_pu', b: 'element_he', result: 'element_cm', type: 'physical', explanation: 'Curium was first produced by bombarding plutonium-239 with alpha particles, represented by helium nuclei.' },
  { a: 'element_am', b: 'element_he', result: 'element_bk', type: 'physical', explanation: 'Berkelium was produced by alpha-particle bombardment of americium-241.' },
  { a: 'element_cm', b: 'element_he', result: 'element_cf', type: 'physical', explanation: 'Californium was produced by alpha-particle bombardment of curium-242.' },
  { a: 'element_cf', b: 'reactor', result: 'element_es', type: 'physical', explanation: 'Einsteinium can be produced in high neutron flux through repeated capture and beta-decay steps; the chain is compressed.' },
  { a: 'element_es', b: 'reactor', result: 'element_fm', type: 'physical', explanation: 'Fermium can be reached in intense neutron-flux capture chains beyond einsteinium; the intermediate isotopes are compressed.' },
  { a: 'element_es', b: 'element_he', result: 'element_md', type: 'physical', explanation: 'Mendelevium was first produced by bombarding einsteinium-253 with alpha particles.' },
  { a: 'element_cm', b: 'element_c', result: 'element_no', type: 'physical', explanation: 'Nobelium isotopes have been produced by bombarding curium targets with carbon ions; isotope details are omitted.' },
  { a: 'element_cf', b: 'element_b', result: 'element_lr', type: 'physical', explanation: 'Lawrencium was first produced by bombarding californium targets with boron ions.' },
  { a: 'element_cf', b: 'element_c', result: 'element_rf', type: 'physical', explanation: 'Rutherfordium-257 was produced from californium-249 and carbon-12 nuclei, with emitted neutrons omitted.' },
  { a: 'element_cf', b: 'element_n', result: 'element_db', type: 'physical', explanation: 'Dubnium isotopes were produced by bombarding californium-249 with nitrogen-15 ions; emitted neutrons are omitted.' },
  { a: 'element_cf', b: 'element_o', result: 'element_sg', type: 'physical', explanation: 'Seaborgium-263 was confirmed using californium-249 targets bombarded with oxygen-18 ions.' },
  { a: 'element_bi', b: 'element_cr', result: 'element_bh', type: 'physical', explanation: 'Bohrium was produced by cold-fusion bombardment of bismuth-209 with chromium-54 ions.' },
  { a: 'element_pb', b: 'element_fe', result: 'element_hs', type: 'physical', explanation: 'Hassium was produced by bombarding lead-208 with iron-58 ions.' },
  { a: 'element_bi', b: 'element_fe', result: 'element_mt', type: 'physical', explanation: 'Meitnerium was produced by bombarding bismuth-209 with iron-58 ions.' },
  { a: 'element_pb', b: 'element_ni', result: 'element_ds', type: 'physical', explanation: 'Darmstadtium was produced by bombarding lead-208 with nickel-62 ions.' },
  { a: 'element_bi', b: 'element_ni', result: 'element_rg', type: 'physical', explanation: 'Roentgenium was produced by bombarding bismuth-209 with nickel-64 ions.' },
  { a: 'element_pb', b: 'element_zn', result: 'element_cn', type: 'physical', explanation: 'Copernicium was produced by bombarding lead-208 with zinc-70 ions.' },
  { a: 'element_bi', b: 'element_zn', result: 'element_nh', type: 'physical', explanation: 'Nihonium was directly produced at RIKEN by bombarding bismuth-209 with zinc-70 ions.' },
  { a: 'element_pu', b: 'element_ca', result: 'element_fl', type: 'physical', explanation: 'Flerovium was produced by hot fusion of plutonium-244 targets with calcium-48 ions.' },
  { a: 'element_am', b: 'element_ca', result: 'element_mc', type: 'physical', explanation: 'Moscovium was produced by hot fusion of americium-243 targets with calcium-48 ions.' },
  { a: 'element_cm', b: 'element_ca', result: 'element_lv', type: 'physical', explanation: 'Livermorium was produced by hot fusion of curium-245 or curium-248 targets with calcium-48 ions.' },
  { a: 'element_bk', b: 'element_ca', result: 'element_ts', type: 'physical', explanation: 'Tennessine was produced by hot fusion of berkelium-249 targets with calcium-48 ions.' },
  { a: 'element_cf', b: 'element_ca', result: 'element_og', type: 'physical', explanation: 'Oganesson was produced by hot fusion of californium-249 targets with calcium-48 ions.' },
]
