/* ─── DESCRIPTIONS FOR EXISTING ELEMENTS ─── */
el('water','Water','💧','Basics',[],{description:'A transparent, tasteless liquid essential for all known life. Chemical formula H2O.'})
el('fire','Fire','🔥','Basics',[],{description:'A rapid exothermic oxidation reaction producing heat and light. One of the classical elements.'})
el('air','Air','💨','Basics',[],{description:'The invisible mixture of gases surrounding Earth, primarily nitrogen and oxygen.'})
el('earth','Earth','🌍','Basics',[],{description:'Soil and rock constituting the solid surface of the planet. One of the classical elements.'})
el('energy','Energy','⚡','Physics',[],{description:'The quantitative property that must be transferred to an object to perform work or heat it.'})
el('life','Life','🧬','Biology',[],{description:'The condition that distinguishes active organisms from inorganic matter, characterized by growth and reproduction.'})
el('plant','Plant','🌱','Nature',[],{description:'A living organism that synthesizes energy from sunlight through photosynthesis.'})
el('time','Time','⏳','Abstract',[],{description:'The indefinite continued progress of existence and events in the past, present, and future.'})
el('space','Space','🌌','Abstract',[],{description:'The boundless three-dimensional extent in which objects and events have relative position and direction.'})
el('science','Science','🔬','Science',[],{description:'The systematic enterprise that builds and organizes knowledge in the form of testable explanations.'})
el('chemistry','Chemistry','⚗️','Science',[],{description:'The branch of science concerned with the properties and behavior of matter and chemical reactions.'})
el('physics','Physics','🔭','Science',[],{description:'The natural science that studies matter, its motion and behavior through space and time.'})
el('biology','Biology','🧬','Science',[],{description:'The natural science that studies life and living organisms.'})
el('astronomy','Astronomy','🔭','Science',[],{description:'The natural science that studies celestial objects and phenomena beyond Earth.'})
el('steam','Steam','♨️','Physics',[],{description:'Water in its gaseous state, formed when water is heated to its boiling point (100°C).'})
el('ice','Ice','🧊','Weather',[],{description:'Water in its solid crystalline state, formed when water freezes at 0°C (32°F).'})
el('cloud','Cloud','☁️','Weather',[],{description:'A visible mass of condensed water droplets or ice crystals suspended in the atmosphere.'})
el('rain','Rain','🌧️','Weather',[],{description:'Liquid water falling from clouds in the form of droplets condensed from atmospheric water vapor.'})
el('snow','Snow','❄️','Weather',[],{description:'Precipitation in the form of ice crystals falling from clouds.'})
el('cold','Cold','🥶','Weather',[],{description:'The subjective perception of low temperature, the absence of heat.'})
el('metal','Metal','🔩','Materials',[],{description:'A solid material that is typically hard, shiny, malleable, fusible, and ductile with good electrical conductivity.'})
el('wood','Wood','🪵','Materials',[],{description:'The hard fibrous structural tissue found in the stems and roots of trees and other woody plants.'})
el('stone','Stone','🪨','Geology',[],{description:'Hard, solid non-metallic mineral material that forms the Earth crust.'})
el('sand','Sand','🏖️','Geology',[],{description:'A granular material composed of finely divided rock and mineral particles.'})
el('glass','Glass','🪟','Materials',[],{description:'A hard, brittle, usually transparent or translucent material made by fusing sand with soda and lime.'})
el('iron','Iron','⛓️','Materials',[],{description:'A strong, hard magnetic silvery-gray metal. Atomic number 26. Essential for steel production.'})
el('gold','Gold','🥇','Materials',[],{description:'A precious yellow metallic element. Atomic number 79. Highly malleable and resistant to corrosion.'})
el('copper','Copper','🪙','Materials',[],{description:'A reddish-brown metal. Atomic number 29. Excellent conductor of electricity and heat.'})
el('silver','Silver','🥈','Materials',[],{description:'A precious white metallic element. Atomic number 47. Best known conductor of electricity.'})
el('steel','Steel','⚙️','Materials',[],{description:'An alloy of iron and carbon, stronger and harder than pure iron. The foundation of modern industry.'})
el('diamond','Diamond','💎','Materials',[],{description:'An extremely hard crystalline form of carbon. The hardest known natural material on Earth.'})
el('coal','Coal','🪨','Energy',[],{description:'A combustible black sedimentary rock composed mainly of carbon, formed from ancient plant matter.'})
el('oil','Oil','🛢️','Energy',[],{description:'A viscous liquid hydrocarbon formed from ancient organic matter under heat and pressure.'})
el('gas','Gas','⛽','Energy',[],{description:'A fossil fuel composed mainly of methane, used for heating, cooking, and electricity generation.'})
el('electricity','Electricity','⚡','Energy',[],{description:'A form of energy resulting from the flow of charged particles such as electrons.'})
el('human','Human','🧑','Biology',[],{description:'A member of the species Homo sapiens, characterized by bipedalism and advanced cognitive abilities.'})
el('tool','Tool','🔧','Tools',[],{description:'A device or implement used to carry out a particular function, extending human capability.'})
el('machine','Machine','⚙️','Technology',[],{description:'An apparatus using mechanical power to perform a specific task.'})
el('computer','Computer','💻','Technology',[],{description:'An electronic device for storing and processing data according to programmed instructions.'})
el('internet','Internet','🌐','Technology',[],{description:'The global computer network providing worldwide information and communication connectivity.'})
el('sun','Sun','☀️','Space',[],{description:'The star at the center of Solar System, a nearly perfect sphere of hot plasma that provides light and heat to Earth.'})
el('star','Star','⭐','Space',[],{description:'A luminous sphere of plasma held together by gravity, generating energy through nuclear fusion.'})
el('planet','Planet','🪐','Space',[],{description:'A large celestial body orbiting a star, massive enough to have cleared its orbital neighborhood.'})
el('moon','Moon','🌙','Space',[],{description:'A natural satellite that orbits a planet. Earth only permanent natural satellite.'})
el('galaxy','Galaxy','🌌','Space',[],{description:'A vast system of stars, gas, dust, and dark matter bound together by gravity.'})
el('atom','Atom','⚛️','Science',[],{description:'The smallest unit of ordinary matter that retains the properties of a chemical element.'})
el('molecule','Molecule','🧬','Science',[],{description:'A group of atoms bonded together, representing the smallest fundamental unit of a chemical compound.'})
el('dna','DNA','🧬','Biology',[],{description:'Deoxyribonucleic acid, the molecule that carries genetic instructions for development and function of living organisms.'})
el('cell','Cell','🔬','Biology',[],{description:'The basic structural and functional unit of all known living organisms.'})
el('brain','Brain','🧠','Biology',[],{description:'The organ that serves as the center of the nervous system in all vertebrate and most invertebrate animals.'})
el('heart','Heart','❤️','Biology',[],{description:'A muscular organ that pumps blood through the circulatory system of animals.'})
el('mud','Mud','🧴','Earth',[],{description:'A mixture of water and soil or dust, forming a semi-liquid substance.'})
el('lava','Lava','🌋','Geology',[],{description:'Molten rock expelled by a volcano during an eruption, reaching temperatures of 700-1,200°C.'})
el('dust','Dust','🏜️','Earth',[],{description:'Fine particles of matter, typically dry earth or organic material suspended in the air.'})
el('rainbow','Rainbow','🌈','Weather',[],{description:'An optical phenomenon caused by refraction and reflection of light in water droplets, producing a spectrum of colors.'})
el('lightning','Lightning','⚡','Weather',[],{description:'A sudden electrostatic discharge during a thunderstorm, producing a bright flash of light.'})
el('storm','Storm','⛈️','Weather',[],{description:'A violent disturbance of the atmosphere with strong winds and usually rain, thunder, or snow.'})
el('wind','Wind','💨','Weather',[],{description:'The natural movement of air, especially in the form of a current blowing from a particular direction.'})
el('ocean','Ocean','🌊','Geography',[],{description:'A vast body of salt water covering about 71% of Earth surface.'})
el('river','River','🏞️','Geography',[],{description:'A natural flowing watercourse, usually freshwater, flowing toward an ocean, sea, or lake.'})
el('mountain','Mountain','⛰️','Geology',[],{description:'A large natural elevation of the Earth surface rising abruptly from the surrounding level.'})
el('volcano','Volcano','🌋','Geology',[],{description:'A rupture in the Earth crust through which lava, ash, and gases are ejected from below the surface.'})
el('tree','Tree','🌳','Nature',[],{description:'A perennial woody plant with a single main trunk, branches, and leaves.'})
el('flower','Flower','🌸','Nature',[],{description:'The reproductive structure of flowering plants, often colorful and fragrant.'})
el('seed','Seed','🌱','Agriculture',[],{description:'An embryonic plant enclosed in a protective outer covering, capable of developing into a new plant.'})
el('fruit','Fruit','🍎','Food',[],{description:'The seed-bearing structure in flowering plants, often sweet and edible.'})
el('soil','Soil','🫘','Earth',[],{description:'The upper layer of Earth surface composed of organic matter, minerals, water, and air.'})
el('clay','Clay','🏺','Materials',[],{description:'A fine-grained natural soil material that becomes plastic when wet and hardens when fired.'})
el('mineral','Mineral','💎','Geology',[],{description:'A naturally occurring inorganic solid with a definite chemical composition and crystalline structure.'})
el('fossil','Fossil','🦴','Geology',[],{description:'The preserved remains or traces of ancient organisms preserved in rock.'})
el('obsidian','Obsidian','🪨','Geology',[],{description:'A naturally occurring volcanic glass formed when lava cools rapidly with minimal crystal growth.'})
el('brick','Brick','🧱','Construction',[],{description:'A rectangular block of fired clay used in building construction, bonded with mortar.'})
el('concrete','Concrete','🏗️','Construction',[],{description:'A composite building material made from cement, aggregate, and water that hardens over time.'})
el('plastic','Plastic','🧴','Materials',[],{description:'A synthetic polymer material that can be molded into various shapes, widely used in manufacturing.'})
el('battery','Battery','🔋','Energy',[],{description:'A device that stores chemical energy and converts it into electrical energy.'})
el('wire','Wire','🔌','Technology',[],{description:'A thin flexible thread of metal used to carry electrical current.'})
el('wheel','Wheel','⚙️','Tools',[],{description:'A circular component that rotates on an axle, fundamental to transportation and machinery.'})
el('paper','Paper','📄','Materials',[],{description:'A thin material produced by pressing together moist fibers of cellulose from wood.'})
el('fabric','Fabric','🧵','Materials',[],{description:'A flexible material made by weaving or knitting fibers together.'})
el('rope','Rope','🪢','Materials',[],{description:'A strong thick cord made of twisted or braided fibers.'})
el('ceramic','Ceramic','🏺','Materials',[],{description:'A hard, brittle material made by firing clay or other inorganic materials at high temperatures.'})
el('medicine','Medicine','💊','Biology',[],{description:'A substance used for treating or preventing disease.'})
el('hospital','Hospital','🏥','Society',[],{description:'A medical facility providing patient treatment with specialized staff and equipment.'})
el('laboratory','Laboratory','🧪','Science',[],{description:'A facility providing controlled conditions for scientific research and experimentation.'})
el('factory','Factory','🏭','Industry',[],{description:'An industrial building where goods are manufactured or assembled by machine.'})
el('food','Food','🍽️','Food',[],{description:'Any nutritious substance consumed to sustain life, providing energy and essential nutrients.'})
el('cooking','Cooking','🍳','Food',[],{description:'The art and science of preparing food by applying heat for human consumption.'})
el('bread','Bread','🍞','Food',[],{description:'A staple food made from dough of flour and water, usually baked.'})
el('cheese','Cheese','🧀','Food',[],{description:'A dairy product made from milk curds, available in hundreds of varieties worldwide.'})
el('wine','Wine','🍷','Food',[],{description:'An alcoholic beverage made from fermented grapes.'})
el('beer','Beer','🍺','Food',[],{description:'One of the oldest alcoholic beverages, made from fermented grains, usually barley.'})
el('salt','Salt','🧂','Food',[],{description:'Sodium chloride, a mineral essential for life and used as a seasoning for food.'})
el('sugar','Sugar','🍬','Food',[],{description:'A sweet crystalline substance obtained from sugar cane or sugar beet, used as a sweetener.'})
el('honey','Honey','🍯','Food',[],{description:'A sweet viscous substance produced by bees from flower nectar.'})
el('milk','Milk','🥛','Food',[],{description:'A nutrient-rich liquid produced by mammals as food for their young.'})
el('meat','Meat','🥩','Food',[],{description:'Animal flesh used as food, a primary source of protein for humans.'})
el('music','Music','🎵','Culture',[],{description:'An art form and cultural activity whose medium is sound organized in time.'})
el('book','Book','📖','Culture',[],{description:'A written or printed work consisting of pages bound together, containing knowledge or stories.'})
el('art','Art','🎨','Culture',[],{description:'The expression of creative skill and imagination, producing works appreciated for their beauty.'})
el('knowledge','Knowledge','📚','Abstract',[],{description:'Facts, information, and skills acquired through experience or education.'})
el('money','Money','💰','Commerce',[],{description:'A medium of exchange in the form of coins and banknotes used for transactions.'})
el('city','City','🏙️','Society',[],{description:'A large permanent human settlement with complex systems for sanitation, utilities, and governance.'})
el('house','House','🏠','Construction',[],{description:'A building for human habitation, providing shelter and living space.'})
el('village','Village','🏘️','Society',[],{description:'A small human settlement smaller than a town, typically in a rural area.'})
el('car','Car','🚗','Transport',[],{description:'A four-wheeled road vehicle powered by an engine, used for personal transportation.'})
el('train','Train','🚂','Transport',[],{description:'A series of connected rail vehicles that run along railway tracks for transporting passengers or freight.'})
el('plane','Plane','✈️','Transport',[],{description:'A powered flying vehicle with fixed wings that is heavier than air.'})
el('ship','Ship','🚢','Transport',[],{description:'A large watercraft that travels the world oceans and seas for transport of goods or people.'})
el('rocket','Rocket','🚀','Space',[],{description:'A spacecraft or vehicle that travels through space by expelling exhaust gases at high speed.'})
el('astronaut','Astronaut','🧑‍🚀','Space',[],{description:'A person trained to travel and work in space aboard a spacecraft.'})
el('satellite','Satellite','🛰️','Space',[],{description:'An object placed into orbit around a celestial body for communication, observation, or research.'})
el('robot','Robot','🤖','Technology',[],{description:'A programmable machine capable of carrying out complex tasks autonomously or by remote control.'})
el('ai','AI','🧠','Technology',[],{description:'Artificial intelligence: the simulation of human intelligence processes by computer systems.'})
el('nuclear','Nuclear','☢️','Energy',[],{description:'Relating to the nucleus of an atom, involving reactions that release enormous energy by splitting or fusing nuclei.'})
el('mining','Mining','⛏️','Industry',[],{description:'The process of extracting valuable minerals or other geological materials from the Earth.'})
el('smelting','Smelting','🔥','Industry',[],{description:'The process of extracting metal from ore by heating and melting it.'})
el('construction','Construction','🏗️','Construction',[],{description:'The process of building structures or infrastructure using materials like wood, steel, and concrete.'})
el('transport','Transport','🚗','Transport',[],{description:'The system or means of moving people or goods from one place to another.'})
el('industry','Industry','🏭','Industry',[],{description:'Economic activity involving the processing of raw materials and manufacture of goods in factories.'})
el('culture','Culture','🎭','Culture',[],{description:'The customs, arts, social institutions, and achievements of a particular nation or group.'})
el('society','Society','🏛️','Society',[],{description:'A community of people living together in an organized way with shared customs and laws.'})
el('government','Government','🏛️','Society',[],{description:'The governing body of a nation or community, exercising authority and making policy.'})
el('law','Law','⚖️','Society',[],{description:'A system of rules created and enforced by institutions to regulate behavior in a society.'})
el('civilization','Civilization','🏛️','Society',[],{description:'An advanced state of human society with developed culture, science, industry, and government.'})
el('war','War','⚔️','Society',[],{description:'A state of armed conflict between different nations, states, or groups.'})
el('magic','Magic','🔮','Fantasy',[],{description:'The use of supernatural forces or powers to influence events, a staple of mythology and fantasy.'})
el('dragon','Dragon','🐉','Fantasy',[],{description:'A legendary reptilian creature with wings, capable of breathing fire, found in folklore worldwide.'})
el('mythology','Mythology','📜','Fantasy',[],{description:'A collection of myths belonging to a particular culture or religion, explaining aspects of the natural world.'})
el('universe','Universe','🌌','Space',[],{description:'All of space and time and their contents, including planets, stars, galaxies, and all forms of matter and energy.'})

/* ─── PERIODIC TABLE — ALL 118 ELEMENTS ─── */
el('element_h','Hydrogen','🧪','Chemistry',['element','chemistry'],{description:'Hydrogen (H). The lightest and most abundant chemical element in the universe. Atomic number 1.','symbol':'H','atomicNumber':1,'chemicalGroup':'Nonmetal'})
el('element_he','Helium','🧪','Chemistry',['element','chemistry'],{description:'Helium (He). A colorless, odorless, tasteless noble gas. Atomic number 2. Second lightest element.','symbol':'He','atomicNumber':2,'chemicalGroup':'Noble gas'})
el('element_li','Lithium','🧪','Chemistry',['element','chemistry'],{description:'Lithium (Li). A soft, silvery-white alkali metal. Atomic number 3. Lightest metal and solid element.','symbol':'Li','atomicNumber':3,'chemicalGroup':'Alkali metal'})
el('element_be','Beryllium','🧪','Chemistry',['element','chemistry'],{description:'Beryllium (Be). A hard, grayish alkaline earth metal. Atomic number 4. Lightweight and high melting point.','symbol':'Be','atomicNumber':4,'chemicalGroup':'Alkaline earth metal'})
el('element_b','Boron','🧪','Chemistry',['element','chemistry'],{description:'Boron (B). A metalloid element. Atomic number 5. Used in semiconductors and borosilicate glass.','symbol':'B','atomicNumber':5,'chemicalGroup':'Metalloid'})
el('element_c','Carbon','🧪','Chemistry',['element','chemistry'],{description:'Carbon (C). The basis of organic chemistry. Atomic number 6. Forms the backbone of all known life.','symbol':'C','atomicNumber':6,'chemicalGroup':'Nonmetal'})
el('element_n','Nitrogen','🧪','Chemistry',['element','chemistry'],{description:'Nitrogen (N). A colorless, odorless gas. Atomic number 7. Makes up 78% of Earth atmosphere.','symbol':'N','atomicNumber':7,'chemicalGroup':'Nonmetal'})
el('element_o','Oxygen','🧪','Chemistry',['element','chemistry'],{description:'Oxygen (O). A highly reactive gas essential for respiration. Atomic number 8. Makes up 21% of air.','symbol':'O','atomicNumber':8,'chemicalGroup':'Nonmetal'})
el('element_f','Fluorine','🧪','Chemistry',['element','chemistry'],{description:'Fluorine (F). A pale yellow halogen gas. Atomic number 9. The most electronegative and reactive element.','symbol':'F','atomicNumber':9,'chemicalGroup':'Halogen'})
el('element_ne','Neon','🧪','Chemistry',['element','chemistry'],{description:'Neon (Ne). A colorless noble gas. Atomic number 10. Used in neon signs and high-voltage indicators.','symbol':'Ne','atomicNumber':10,'chemicalGroup':'Noble gas'})
el('element_na','Sodium','🧪','Chemistry',['element','chemistry'],{description:'Sodium (Na). A soft, silvery alkali metal. Atomic number 11. Essential for biological organisms.','symbol':'Na','atomicNumber':11,'chemicalGroup':'Alkali metal'})
el('element_mg','Magnesium','🧪','Chemistry',['element','chemistry'],{description:'Magnesium (Mg). A shiny gray alkaline earth metal. Atomic number 12. Essential for living cells.','symbol':'Mg','atomicNumber':12,'chemicalGroup':'Alkaline earth metal'})
el('element_al','Aluminium','🧪','Chemistry',['element','chemistry'],{description:'Aluminium (Al). A silvery-white, lightweight metal. Atomic number 13. Most abundant metal in Earth crust.','symbol':'Al','atomicNumber':13,'chemicalGroup':'Post-transition metal'})
el('element_si','Silicon','🧪','Chemistry',['element','chemistry'],{description:'Silicon (Si). A hard, brittle crystalline metalloid. Atomic number 14. Widely used in semiconductors and electronics.','symbol':'Si','atomicNumber':14,'chemicalGroup':'Metalloid'})
el('element_p','Phosphorus','🧪','Chemistry',['element','chemistry'],{description:'Phosphorus (P). A reactive nonmetal. Atomic number 15. Essential for DNA, RNA, and ATP.','symbol':'P','atomicNumber':15,'chemicalGroup':'Nonmetal'})
el('element_s','Sulfur','🧪','Chemistry',['element','chemistry'],{description:'Sulfur (S). A yellow crystalline nonmetal. Atomic number 16. Used in gunpowder and sulfuric acid.','symbol':'S','atomicNumber':16,'chemicalGroup':'Nonmetal'})
el('element_cl','Chlorine','🧪','Chemistry',['element','chemistry'],{description:'Chlorine (Cl). A yellow-green halogen gas. Atomic number 17. Used as a disinfectant and bleach.','symbol':'Cl','atomicNumber':17,'chemicalGroup':'Halogen'})
el('element_ar','Argon','🧪','Chemistry',['element','chemistry'],{description:'Argon (Ar). A colorless, odorless noble gas. Atomic number 18. Most abundant noble gas in Earth atmosphere.','symbol':'Ar','atomicNumber':18,'chemicalGroup':'Noble gas'})
el('element_k','Potassium','🧪','Chemistry',['element','chemistry'],{description:'Potassium (K). A soft, silvery alkali metal. Atomic number 19. Essential for nerve function and muscle contraction.','symbol':'K','atomicNumber':19,'chemicalGroup':'Alkali metal'})
el('element_ca','Calcium','🧪','Chemistry',['element','chemistry'],{description:'Calcium (Ca). A soft gray alkaline earth metal. Atomic number 20. Essential for bones, teeth, and cellular signaling.','symbol':'Ca','atomicNumber':20,'chemicalGroup':'Alkaline earth metal'})
el('element_sc','Scandium','🧪','Chemistry',['element','chemistry'],{description:'Scandium (Sc). A silvery-white metallic transition metal. Atomic number 21. Used in aerospace alloys.','symbol':'Sc','atomicNumber':21,'chemicalGroup':'Transition metal'})
el('element_ti','Titanium','🧪','Chemistry',['element','chemistry'],{description:'Titanium (Ti). A lustrous transition metal with low density and high strength. Atomic number 22.','symbol':'Ti','atomicNumber':22,'chemicalGroup':'Transition metal'})
el('element_v','Vanadium','🧪','Chemistry',['element','chemistry'],{description:'Vanadium (V). A hard, silvery-grey transition metal. Atomic number 23. Used in steel alloys.','symbol':'V','atomicNumber':23,'chemicalGroup':'Transition metal'})
el('element_cr','Chromium','🧪','Chemistry',['element','chemistry'],{description:'Chromium (Cr). A shiny grey transition metal. Atomic number 24. Provides corrosion resistance in stainless steel.','symbol':'Cr','atomicNumber':24,'chemicalGroup':'Transition metal'})
el('element_mn','Manganese','🧪','Chemistry',['element','chemistry'],{description:'Manganese (Mn). A hard, brittle silvery transition metal. Atomic number 25. Essential for steel production.','symbol':'Mn','atomicNumber':25,'chemicalGroup':'Transition metal'})
el('element_fe','Iron','🧪','Chemistry',['element','chemistry'],{description:'Iron (Fe). A strong, hard magnetic silvery-gray transition metal. Atomic number 26. Essential for steel and hemoglobin.','symbol':'Fe','atomicNumber':26,'chemicalGroup':'Transition metal'})
el('element_co','Cobalt','🧪','Chemistry',['element','chemistry'],{description:'Cobalt (Co). A hard, lustrous gray transition metal. Atomic number 27. Used in batteries and blue pigments.','symbol':'Co','atomicNumber':27,'chemicalGroup':'Transition metal'})
el('element_ni','Nickel','🧪','Chemistry',['element','chemistry'],{description:'Nickel (Ni). A silvery-white lustrous transition metal. Atomic number 28. Used in stainless steel and batteries.','symbol':'Ni','atomicNumber':28,'chemicalGroup':'Transition metal'})
el('element_cu','Copper','🧪','Chemistry',['element','chemistry'],{description:'Copper (Cu). A reddish-brown transition metal. Atomic number 29. Excellent conductor of electricity and heat.','symbol':'Cu','atomicNumber':29,'chemicalGroup':'Transition metal'})
el('element_zn','Zinc','🧪','Chemistry',['element','chemistry'],{description:'Zinc (Zn). A bluish-white transition metal. Atomic number 30. Essential for galvanization and biological enzymes.','symbol':'Zn','atomicNumber':30,'chemicalGroup':'Transition metal'})
el('element_ga','Gallium','🧪','Chemistry',['element','chemistry'],{description:'Gallium (Ga). A soft, silvery metal. Atomic number 31. Melts in the hand at 29.7°C.','symbol':'Ga','atomicNumber':31,'chemicalGroup':'Post-transition metal'})
el('element_ge','Germanium','🧪','Chemistry',['element','chemistry'],{description:'Germanium (Ge). A lustrous, hard-brittle metalloid. Atomic number 32. Used in fiber optics and semiconductors.','symbol':'Ge','atomicNumber':32,'chemicalGroup':'Metalloid'})
el('element_as','Arsenic','🧪','Chemistry',['element','chemistry'],{description:'Arsenic (As). A brittle, steel-gray metalloid. Atomic number 33. Known for its toxicity.','symbol':'As','atomicNumber':33,'chemicalGroup':'Metalloid'})
el('element_se','Selenium','🧪','Chemistry',['element','chemistry'],{description:'Selenium (Se). A nonmetal with reddish color. Atomic number 34. Essential trace element for living organisms.','symbol':'Se','atomicNumber':34,'chemicalGroup':'Nonmetal'})
el('element_br','Bromine','🧪','Chemistry',['element','chemistry'],{description:'Bromine (Br). A reddish-brown halogen liquid. Atomic number 35. The only nonmetallic element liquid at room temperature.','symbol':'Br','atomicNumber':35,'chemicalGroup':'Halogen'})
el('element_kr','Krypton','🧪','Chemistry',['element','chemistry'],{description:'Krypton (Kr). A colorless noble gas. Atomic number 36. Used in high-performance light bulbs.','symbol':'Kr','atomicNumber':36,'chemicalGroup':'Noble gas'})
el('element_rb','Rubidium','🧪','Chemistry',['element','chemistry'],{description:'Rubidium (Rb). A soft, silvery-white alkali metal. Atomic number 37. Highly reactive.','symbol':'Rb','atomicNumber':37,'chemicalGroup':'Alkali metal'})
el('element_sr','Strontium','🧪','Chemistry',['element','chemistry'],{description:'Strontium (Sr). A soft, silvery alkaline earth metal. Atomic number 38. Used in fireworks for red color.','symbol':'Sr','atomicNumber':38,'chemicalGroup':'Alkaline earth metal'})
el('element_y','Yttrium','🧪','Chemistry',['element','chemistry'],{description:'Yttrium (Y). A silvery-metallic transition metal. Atomic number 39. Used in LEDs and superconductors.','symbol':'Y','atomicNumber':39,'chemicalGroup':'Transition metal'})
el('element_zr','Zirconium','🧪','Chemistry',['element','chemistry'],{description:'Zirconium (Zr). A lustrous gray-white transition metal. Atomic number 40. Used in nuclear reactors.','symbol':'Zr','atomicNumber':40,'chemicalGroup':'Transition metal'})
el('element_nb','Niobium','🧪','Chemistry',['element','chemistry'],{description:'Niobium (Nb). A shiny gray transition metal. Atomic number 41. Used in superconducting magnets.','symbol':'Nb','atomicNumber':41,'chemicalGroup':'Transition metal'})
el('element_mo','Molybdenum','🧪','Chemistry',['element','chemistry'],{description:'Molybdenum (Mo). A silvery transition metal. Atomic number 42. Used in high-strength steel alloys.','symbol':'Mo','atomicNumber':42,'chemicalGroup':'Transition metal'})
el('element_tc','Technetium','🧪','Chemistry',['element','chemistry'],{description:'Technetium (Tc). A silvery-gray transition metal. Atomic number 43. The lightest element with no stable isotopes.','symbol':'Tc','atomicNumber':43,'chemicalGroup':'Transition metal'})
el('element_ru','Ruthenium','🧪','Chemistry',['element','chemistry'],{description:'Ruthenium (Ru). A hard, white transition metal. Atomic number 44. Used in electrical contacts.','symbol':'Ru','atomicNumber':44,'chemicalGroup':'Transition metal'})
el('element_rh','Rhodium','🧪','Chemistry',['element','chemistry'],{description:'Rhodium (Rh). A silvery-white transition metal. Atomic number 45. One of the rarest precious metals.','symbol':'Rh','atomicNumber':45,'chemicalGroup':'Transition metal'})
el('element_pd','Palladium','🧪','Chemistry',['element','chemistry'],{description:'Palladium (Pd). A lustrous silvery-white transition metal. Atomic number 46. Used in catalytic converters.','symbol':'Pd','atomicNumber':46,'chemicalGroup':'Transition metal'})
el('element_ag','Silver','🧪','Chemistry',['element','chemistry'],{description:'Silver (Ag). A white lustrous transition metal. Atomic number 47. Best conductor of electricity.','symbol':'Ag','atomicNumber':47,'chemicalGroup':'Transition metal'})
el('element_cd','Cadmium','🧪','Chemistry',['element','chemistry'],{description:'Cadmium (Cd). A soft, bluish-white transition metal. Atomic number 48. Used in rechargeable batteries.','symbol':'Cd','atomicNumber':48,'chemicalGroup':'Transition metal'})
el('element_in','Indium','🧪','Chemistry',['element','chemistry'],{description:'Indium (In). A soft, silvery post-transition metal. Atomic number 49. Used in touchscreens and solar panels.','symbol':'In','atomicNumber':49,'chemicalGroup':'Post-transition metal'})
el('element_sn','Tin','🧪','Chemistry',['element','chemistry'],{description:'Tin (Sn). A silvery post-transition metal. Atomic number 50. Used in alloys and food packaging.','symbol':'Sn','atomicNumber':50,'chemicalGroup':'Post-transition metal'})
el('element_sb','Antimony','🧪','Chemistry',['element','chemistry'],{description:'Antimony (Sb). A brittle, silvery metalloid. Atomic number 51. Used in flame retardants.','symbol':'Sb','atomicNumber':51,'chemicalGroup':'Metalloid'})
el('element_te','Tellurium','🧪','Chemistry',['element','chemistry'],{description:'Tellurium (Te). A brittle, silver-white metalloid. Atomic number 52. Used in thermoelectric materials.','symbol':'Te','atomicNumber':52,'chemicalGroup':'Metalloid'})
el('element_i','Iodine','🧪','Chemistry',['element','chemistry'],{description:'Iodine (I). A purple-black halogen. Atomic number 53. Essential for thyroid function.','symbol':'I','atomicNumber':53,'chemicalGroup':'Halogen'})
el('element_xe','Xenon','🧪','Chemistry',['element','chemistry'],{description:'Xenon (Xe). A colorless, heavy noble gas. Atomic number 54. Used in flash lamps and ion thrusters.','symbol':'Xe','atomicNumber':54,'chemicalGroup':'Noble gas'})
el('element_cs','Caesium','🧪','Chemistry',['element','chemistry'],{description:'Caesium (Cs). A soft, silvery-gold alkali metal. Atomic number 55. One of the most reactive metals.','symbol':'Cs','atomicNumber':55,'chemicalGroup':'Alkali metal'})
el('element_ba','Barium','🧪','Chemistry',['element','chemistry'],{description:'Barium (Ba). A soft, silvery alkaline earth metal. Atomic number 56. Used in medical X-ray imaging.','symbol':'Ba','atomicNumber':56,'chemicalGroup':'Alkaline earth metal'})
el('element_la','Lanthanum','🧪','Chemistry',['element','chemistry'],{description:'Lanthanum (La). A soft, malleable silvery-white rare earth metal. Atomic number 57.','symbol':'La','atomicNumber':57,'chemicalGroup':'Lanthanide'})
el('element_ce','Cerium','🧪','Chemistry',['element','chemistry'],{description:'Cerium (Ce). A soft, silvery rare earth metal. Atomic number 58. Most abundant rare earth element.','symbol':'Ce','atomicNumber':58,'chemicalGroup':'Lanthanide'})
el('element_pr','Praseodymium','🧪','Chemistry',['element','chemistry'],{description:'Praseodymium (Pr). A yellowish rare earth metal. Atomic number 59. Used in high-strength magnets.','symbol':'Pr','atomicNumber':59,'chemicalGroup':'Lanthanide'})
el('element_nd','Neodymium','🧪','Chemistry',['element','chemistry'],{description:'Neodymium (Nd). A silvery-gold rare earth metal. Atomic number 60. Used in powerful permanent magnets.','symbol':'Nd','atomicNumber':60,'chemicalGroup':'Lanthanide'})
el('element_pm','Promethium','🧪','Chemistry',['element','chemistry'],{description:'Promethium (Pm). A rare earth metal. Atomic number 61. Radioactive with no stable isotopes.','symbol':'Pm','atomicNumber':61,'chemicalGroup':'Lanthanide'})
el('element_sm','Samarium','🧪','Chemistry',['element','chemistry'],{description:'Samarium (Sm). A silvery rare earth metal. Atomic number 62. Used in high-temperature magnets.','symbol':'Sm','atomicNumber':62,'chemicalGroup':'Lanthanide'})
el('element_eu','Europium','🧪','Chemistry',['element','chemistry'],{description:'Europium (Eu). A silvery rare earth metal. Atomic number 63. Used in red phosphors for displays.','symbol':'Eu','atomicNumber':63,'chemicalGroup':'Lanthanide'})
el('element_gd','Gadolinium','🧪','Chemistry',['element','chemistry'],{description:'Gadolinium (Gd). A silvery-white rare earth metal. Atomic number 64. Used in MRI contrast agents.','symbol':'Gd','atomicNumber':64,'chemicalGroup':'Lanthanide'})
el('element_tb','Terbium','🧪','Chemistry',['element','chemistry'],{description:'Terbium (Tb). A silvery-gray rare earth metal. Atomic number 65. Used in solid-state devices.','symbol':'Tb','atomicNumber':65,'chemicalGroup':'Lanthanide'})
el('element_dy','Dysprosium','🧪','Chemistry',['element','chemistry'],{description:'Dysprosium (Dy). A silvery rare earth metal. Atomic number 66. Used in high-strength magnets.','symbol':'Dy','atomicNumber':66,'chemicalGroup':'Lanthanide'})
el('element_ho','Holmium','🧪','Chemistry',['element','chemistry'],{description:'Holmium (Ho). A silvery rare earth metal. Atomic number 67. Highest magnetic strength of any element.','symbol':'Ho','atomicNumber':67,'chemicalGroup':'Lanthanide'})
el('element_er','Erbium','🧪','Chemistry',['element','chemistry'],{description:'Erbium (Er). A silvery-white rare earth metal. Atomic number 68. Used in fiber optics.','symbol':'Er','atomicNumber':68,'chemicalGroup':'Lanthanide'})
el('element_tm','Thulium','🧪','Chemistry',['element','chemistry'],{description:'Thulium (Tm). A silvery-gray rare earth metal. Atomic number 69. Least abundant stable rare earth.','symbol':'Tm','atomicNumber':69,'chemicalGroup':'Lanthanide'})
el('element_yb','Ytterbium','🧪','Chemistry',['element','chemistry'],{description:'Ytterbium (Yb). A silvery rare earth metal. Atomic number 70. Used in atomic clocks.','symbol':'Yb','atomicNumber':70,'chemicalGroup':'Lanthanide'})
el('element_lu','Lutetium','🧪','Chemistry',['element','chemistry'],{description:'Lutetium (Lu). A silvery-white rare earth metal. Atomic number 71. Heaviest and hardest lanthanide.','symbol':'Lu','atomicNumber':71,'chemicalGroup':'Lanthanide'})
el('element_hf','Hafnium','🧪','Chemistry',['element','chemistry'],{description:'Hafnium (Hf). A lustrous silvery transition metal. Atomic number 72. Used in nuclear control rods.','symbol':'Hf','atomicNumber':72,'chemicalGroup':'Transition metal'})
el('element_ta','Tantalum','🧪','Chemistry',['element','chemistry'],{description:'Tantalum (Ta). A hard, blue-gray transition metal. Atomic number 73. Highly corrosion resistant.','symbol':'Ta','atomicNumber':73,'chemicalGroup':'Transition metal'})
el('element_w','Tungsten','🧪','Chemistry',['element','chemistry'],{description:'Tungsten (W). A hard, dense gray-white transition metal. Atomic number 74. Highest melting point of all metals.','symbol':'W','atomicNumber':74,'chemicalGroup':'Transition metal'})
el('element_re','Rhenium','🧪','Chemistry',['element','chemistry'],{description:'Rhenium (Re). A silvery-white transition metal. Atomic number 75. One of the rarest elements in Earth crust.','symbol':'Re','atomicNumber':75,'chemicalGroup':'Transition metal'})
el('element_os','Osmium','🧪','Chemistry',['element','chemistry'],{description:'Osmium (Os). A hard, brittle bluish-white transition metal. Atomic number 76. Densest naturally occurring element.','symbol':'Os','atomicNumber':76,'chemicalGroup':'Transition metal'})
el('element_ir','Iridium','🧪','Chemistry',['element','chemistry'],{description:'Iridium (Ir). A hard, brittle silvery-white transition metal. Atomic number 77. Most corrosion-resistant metal.','symbol':'Ir','atomicNumber':77,'chemicalGroup':'Transition metal'})
el('element_pt','Platinum','🧪','Chemistry',['element','chemistry'],{description:'Platinum (Pt). A dense, malleable silvery-white transition metal. Atomic number 78. Used in catalysts and jewelry.','symbol':'Pt','atomicNumber':78,'chemicalGroup':'Transition metal'})
el('element_au','Gold','🧪','Chemistry',['element','chemistry'],{description:'Gold (Au). A precious yellow transition metal. Atomic number 79. Highly malleable and resistant to corrosion.','symbol':'Au','atomicNumber':79,'chemicalGroup':'Transition metal'})
el('element_hg','Mercury','🧪','Chemistry',['element','chemistry'],{description:'Mercury (Hg). A silvery-white liquid transition metal. Atomic number 80. The only metal liquid at room temperature.','symbol':'Hg','atomicNumber':80,'chemicalGroup':'Transition metal'})
el('element_tl','Thallium','🧪','Chemistry',['element','chemistry'],{description:'Thallium (Tl). A soft, gray post-transition metal. Atomic number 81. Highly toxic.','symbol':'Tl','atomicNumber':81,'chemicalGroup':'Post-transition metal'})
el('element_pb','Lead','🧪','Chemistry',['element','chemistry'],{description:'Lead (Pb). A soft, dense post-transition metal. Atomic number 82. Used in batteries and radiation shielding.','symbol':'Pb','atomicNumber':82,'chemicalGroup':'Post-transition metal'})
el('element_bi','Bismuth','🧪','Chemistry',['element','chemistry'],{description:'Bismuth (Bi). A brittle, pinkish post-transition metal. Atomic number 83. Least toxic heavy metal.','symbol':'Bi','atomicNumber':83,'chemicalGroup':'Post-transition metal'})
el('element_po','Polonium','🧪','Chemistry',['element','chemistry'],{description:'Polonium (Po). A rare, highly radioactive metalloid. Atomic number 84. Highly toxic.','symbol':'Po','atomicNumber':84,'chemicalGroup':'Metalloid'})
el('element_at','Astatine','🧪','Chemistry',['element','chemistry'],{description:'Astatine (At). A radioactive halogen. Atomic number 85. Rarest naturally occurring element.','symbol':'At','atomicNumber':85,'chemicalGroup':'Halogen'})
el('element_rn','Radon','🧪','Chemistry',['element','chemistry'],{description:'Radon (Rn). A colorless, radioactive noble gas. Atomic number 86. Produced by decay of radium.','symbol':'Rn','atomicNumber':86,'chemicalGroup':'Noble gas'})
el('element_fr','Francium','🧪','Chemistry',['element','chemistry'],{description:'Francium (Fr). A highly radioactive alkali metal. Atomic number 87. Second rarest naturally occurring element.','symbol':'Fr','atomicNumber':87,'chemicalGroup':'Alkali metal'})
el('element_ra','Radium','🧪','Chemistry',['element','chemistry'],{description:'Radium (Ra). A radioactive alkaline earth metal. Atomic number 88. Undergoes radioactive decay.','symbol':'Ra','atomicNumber':88,'chemicalGroup':'Alkaline earth metal'})
el('element_ac','Actinium','🧪','Chemistry',['element','chemistry'],{description:'Actinium (Ac). A soft, silvery-white radioactive metal. Atomic number 89. First of the actinide series.','symbol':'Ac','atomicNumber':89,'chemicalGroup':'Actinide'})
el('element_th','Thorium','🧪','Chemistry',['element','chemistry'],{description:'Thorium (Th). A weakly radioactive actinide metal. Atomic number 90. Used in nuclear energy research.','symbol':'Th','atomicNumber':90,'chemicalGroup':'Actinide'})
el('element_pa','Protactinium','🧪','Chemistry',['element','chemistry'],{description:'Protactinium (Pa). A dense, silvery-gray radioactive actinide metal. Atomic number 91.','symbol':'Pa','atomicNumber':91,'chemicalGroup':'Actinide'})
el('element_u','Uranium','🧪','Chemistry',['element','chemistry'],{description:'Uranium (U). A silvery-gray radioactive actinide metal. Atomic number 92. Used as nuclear fuel.','symbol':'U','atomicNumber':92,'chemicalGroup':'Actinide'})
el('element_np','Neptunium','🧪','Chemistry',['element','chemistry'],{description:'Neptunium (Np). A silvery metallic radioactive actinide. Atomic number 93. First transuranium element.','symbol':'Np','atomicNumber':93,'chemicalGroup':'Actinide'})
el('element_pu','Plutonium','🧪','Chemistry',['element','chemistry'],{description:'Plutonium (Pu). A radioactive actinide metal. Atomic number 94. Used in nuclear weapons and power.','symbol':'Pu','atomicNumber':94,'chemicalGroup':'Actinide'})
el('element_am','Americium','🧪','Chemistry',['element','chemistry'],{description:'Americium (Am). A radioactive actinide metal. Atomic number 95. Used in smoke detectors.','symbol':'Am','atomicNumber':95,'chemicalGroup':'Actinide'})
el('element_cm','Curium','🧪','Chemistry',['element','chemistry'],{description:'Curium (Cm). A hard, dense radioactive actinide metal. Atomic number 96.','symbol':'Cm','atomicNumber':96,'chemicalGroup':'Actinide'})
el('element_bk','Berkelium','🧪','Chemistry',['element','chemistry'],{description:'Berkelium (Bk). A radioactive actinide metal. Atomic number 97. Named after Berkeley, California.','symbol':'Bk','atomicNumber':97,'chemicalGroup':'Actinide'})
el('element_cf','Californium','🧪','Chemistry',['element','chemistry'],{description:'Californium (Cf). A radioactive actinide metal. Atomic number 98. Used as a neutron source.','symbol':'Cf','atomicNumber':98,'chemicalGroup':'Actinide'})
el('element_es','Einsteinium','🧪','Chemistry',['element','chemistry'],{description:'Einsteinium (Es). A radioactive actinide metal. Atomic number 99. Named after Albert Einstein.','symbol':'Es','atomicNumber':99,'chemicalGroup':'Actinide'})
el('element_fm','Fermium','🧪','Chemistry',['element','chemistry'],{description:'Fermium (Fm). A radioactive actinide metal. Atomic number 100. Named after Enrico Fermi.','symbol':'Fm','atomicNumber':100,'chemicalGroup':'Actinide'})
el('element_md','Mendelevium','🧪','Chemistry',['element','chemistry'],{description:'Mendelevium (Md). A radioactive actinide metal. Atomic number 101. Named after Dmitri Mendeleev.','symbol':'Md','atomicNumber':101,'chemicalGroup':'Actinide'})
el('element_no','Nobelium','🧪','Chemistry',['element','chemistry'],{description:'Nobelium (No). A radioactive actinide metal. Atomic number 102. Named after Alfred Nobel.','symbol':'No','atomicNumber':102,'chemicalGroup':'Actinide'})
el('element_lr','Lawrencium','🧪','Chemistry',['element','chemistry'],{description:'Lawrencium (Lr). A radioactive actinide metal. Atomic number 103. Named after Ernest Lawrence.','symbol':'Lr','atomicNumber':103,'chemicalGroup':'Actinide'})
el('element_rf','Rutherfordium','🧪','Chemistry',['element','chemistry'],{description:'Rutherfordium (Rf). A radioactive transactinide metal. Atomic number 104. Named after Ernest Rutherford.','symbol':'Rf','atomicNumber':104,'chemicalGroup':'Transition metal'})
el('element_db','Dubnium','🧪','Chemistry',['element','chemistry'],{description:'Dubnium (Db). A radioactive transition metal. Atomic number 105. Named after Dubna, Russia.','symbol':'Db','atomicNumber':105,'chemicalGroup':'Transition metal'})
el('element_sg','Seaborgium','🧪','Chemistry',['element','chemistry'],{description:'Seaborgium (Sg). A radioactive transition metal. Atomic number 106. Named after Glenn T. Seaborg.','symbol':'Sg','atomicNumber':106,'chemicalGroup':'Transition metal'})
el('element_bh','Bohrium','🧪','Chemistry',['element','chemistry'],{description:'Bohrium (Bh). A radioactive transition metal. Atomic number 107. Named after Niels Bohr.','symbol':'Bh','atomicNumber':107,'chemicalGroup':'Transition metal'})
el('element_hs','Hassium','🧪','Chemistry',['element','chemistry'],{description:'Hassium (Hs). A radioactive transition metal. Atomic number 108. Named after the Latin name for Hesse.','symbol':'Hs','atomicNumber':108,'chemicalGroup':'Transition metal'})
el('element_mt','Meitnerium','🧪','Chemistry',['element','chemistry'],{description:'Meitnerium (Mt). A radioactive transition metal. Atomic number 109. Named after Lise Meitner.','symbol':'Mt','atomicNumber':109,'chemicalGroup':'Transition metal'})
el('element_ds','Darmstadtium','🧪','Chemistry',['element','chemistry'],{description:'Darmstadtium (Ds). A radioactive transition metal. Atomic number 110. Named after Darmstadt, Germany.','symbol':'Ds','atomicNumber':110,'chemicalGroup':'Transition metal'})
el('element_rg','Roentgenium','🧪','Chemistry',['element','chemistry'],{description:'Roentgenium (Rg). A radioactive transition metal. Atomic number 111. Named after Wilhelm Röntgen.','symbol':'Rg','atomicNumber':111,'chemicalGroup':'Transition metal'})
el('element_cn','Copernicium','🧪','Chemistry',['element','chemistry'],{description:'Copernicium (Cn). A radioactive transition metal. Atomic number 112. Named after Nicolaus Copernicus.','symbol':'Cn','atomicNumber':112,'chemicalGroup':'Transition metal'})
el('element_nh','Nihonium','🧪','Chemistry',['element','chemistry'],{description:'Nihonium (Nh). A radioactive post-transition metal. Atomic number 113. Named after Japan (Nihon).','symbol':'Nh','atomicNumber':113,'chemicalGroup':'Post-transition metal'})
el('element_fl','Flerovium','🧪','Chemistry',['element','chemistry'],{description:'Flerovium (Fl). A radioactive post-transition metal. Atomic number 114. Named after the Flerov Laboratory.','symbol':'Fl','atomicNumber':114,'chemicalGroup':'Post-transition metal'})
el('element_mc','Moscovium','🧪','Chemistry',['element','chemistry'],{description:'Moscovium (Mc). A radioactive post-transition metal. Atomic number 115. Named after Moscow.','symbol':'Mc','atomicNumber':115,'chemicalGroup':'Post-transition metal'})
el('element_lv','Livermorium','🧪','Chemistry',['element','chemistry'],{description:'Livermorium (Lv). A radioactive post-transition metal. Atomic number 116. Named after Livermore, California.','symbol':'Lv','atomicNumber':116,'chemicalGroup':'Post-transition metal'})
el('element_ts','Tennessine','🧪','Chemistry',['element','chemistry'],{description:'Tennessine (Ts). A radioactive halogen. Atomic number 117. Named after Tennessee.','symbol':'Ts','atomicNumber':117,'chemicalGroup':'Halogen'})
el('element_og','Oganesson','🧪','Chemistry',['element','chemistry'],{description:'Oganesson (Og). A radioactive noble gas. Atomic number 118. Named after Yuri Oganessian. Heaviest known element.','symbol':'Og','atomicNumber':118,'chemicalGroup':'Noble gas'})

/* ─── INTEGRATE ELEMENTS INTO DISCOVERY CHAINS ─── */
re('physics','energy','atom','strong')
re('atom','energy','nucleus','strong')
re('nucleus','energy','proton','strong')
re('nucleus','energy','neutron','strong')
re('proton','electron','element_h','strong')
re('star','energy','element_he','strong')
re('life','energy','element_c','strong')
re('plant','air','element_o','strong')
re('water','electricity','element_h','reasonable')
re('water','electricity','element_o','reasonable')
re('star','explosion','element_fe','reasonable')
re('star','supernova','element_au','reasonable')
re('star','supernova','element_ag','reasonable')
re('star','supernova','element_cu','reasonable')
re('star','supernova','element_pt','reasonable')
re('star','supernova','element_pb','reasonable')
re('star','supernova','element_u','reasonable')

/* ─── STRENGTHEN SCIENTIFIC CHAINS ─── */
re('water','cold','ice','strong')
re('water','heat','steam','strong')
re('cloud','cold','snow','strong')
re('sand','heat','glass','strong')
re('plant','time','tree','strong')
re('wood','fire','ash','strong')
re('wood','fire','charcoal','strong')
re('iron','carbon','steel','strong')
re('electricity','metal','wire','strong')
