/* ─── DEEP SCIENCE CHAIN ─── */
el('atom','Atom','⚛️','Science')
re('matter','physics','atom','strong')
el('molecule','Molecule','🧬','Science')
re('atom','chemical','molecule','strong')
el('compound','Chemical Compound','🧪','Science')
re('molecule','reaction','compound','strong')
el('reaction','Chemical Reaction','⚡','Science')
re('compound','energy','reaction','strong')
el('acid','Acid','🧪','Science')
re('sulfur','oxygen','acid','strong')
el('base','Base','🧪','Science')
re('mineral','water','base','strong')
el('experiment','Experiment','🧪','Science')
re('laboratory','reaction','experiment','strong')
el('theory','Theory','📜','Science')
re('science','experiment','theory','strong')

/* ─── DEEP MEDICINE CHAIN ─── */
el('anatomy','Anatomy','🧍','Biology')
re('biology','body','anatomy','strong')
el('cell','Cell','🔬','Biology')
re('life','microscope','cell','strong')
el('tissue_bio','Tissue','🧬','Biology')
re('cell','cell','tissue_bio','strong')
el('organ','Organ','🫀','Biology')
re('tissue_bio','anatomy','organ','strong')
el('heart','Heart','❤️','Biology')
re('organ','blood','heart','strong')
el('lung','Lung','🫁','Biology')
re('organ','air','lung','strong')
el('brain','Brain','🧠','Biology')
re('nerve','organ','brain','strong')
el('nerve','Nerve','🧠','Biology')
re('cell','signal','nerve','strong')
el('blood','Blood','🩸','Biology')
re('cell','water','blood','strong')
el('pharmacy','Pharmacy','💊','Biology')
re('chemistry','medicine','pharmacy','strong')
el('surgery','Surgery','🔪','Biology')
re('medicine','knife','surgery','strong')
el('diagnosis','Diagnosis','🔬','Biology')
re('medicine','microscope','diagnosis','strong')
el('genetics','Genetics','🧬','Science')
re('biology','dna','genetics','strong')

/* ─── DEEP TECHNOLOGY CHAIN ─── */
el('sensor','Sensor','📡','Technology')
re('electronics','detect','sensor','strong')
el('actuator','Actuator','🔧','Technology')
re('motor','control','actuator','strong')
el('drone','Drone','🛸','Technology')
re('hovercraft','robot','drone','strong')
el('3d_printer','3D Printer','🖨️','Technology')
re('computer','manufacturing','3d_printer','strong')
el('virtual_reality','Virtual Reality','🥽','Technology')
re('computer','reality','virtual_reality','strong')
el('cyborg','Cyborg','🦾','Technology')
re('human','robot','cyborg','strong')
el('quantum_computer','Quantum Computer','💻','Technology')
re('computer','quantum','quantum_computer','strong')
el('blockchain','Blockchain','⛓️','Technology')
re('data','chain','blockchain','strong')
el('cryptocurrency','Cryptocurrency','🪙','Technology')
re('blockchain','money','cryptocurrency','strong')
el('firewall','Firewall','🧱','Technology')
re('security','network','firewall','strong')

/* ─── DEEP SPACE CHAIN ─── */
el('launch','Launch','🚀','Space')
re('rocket','fire','launch','strong')
el('space_suit','Space Suit','👨‍🚀','Space')
re('astronaut','fabric','space_suit','strong')
el('fuel_rocket','Rocket Fuel','⛽','Space')
re('oil','chemistry','fuel_rocket','strong')
el('moon_landing','Moon Landing','🌙','Space')
re('spacecraft','moon','moon_landing','strong')
el('space_telescope','Space Telescope','🔭','Space')
re('telescope','satellite','space_telescope','strong')
el('space_station','Space Station','🛰️','Space')
re('satellite','habitat','space_station','strong')
el('exoplanet','Exoplanet','🪐','Space')
re('star','planet','exoplanet','strong')
el('supernova','Supernova','💥','Space')
re('star','explosion','supernova','strong')
el('neutron_star','Neutron Star','⭐','Space')
re('supernova','gravity','neutron_star','strong')
el('pulsar','Pulsar','⭐','Space')
re('neutron_star','spin','pulsar','strong')
el('black_hole','Black Hole','🕳️','Space')
re('neutron_star','collapse','black_hole','strong')
el('nebula','Nebula','🌌','Space')
re('star','cloud','nebula','strong')
el('constellation','Constellation','⭐','Space')
re('star','pattern','constellation','strong')
el('space_colony','Space Colony','🚀','Space')
re('space_station','city','space_colony','strong')
el('mars_colony','Mars Colony','🪐','Space')
re('rocket','mars','mars_colony','strong')

/* ─── BUILDING/ARCHITECTURE ─── */
el('skyscraper','Skyscraper','🏙️','Construction')
re('building','steel','skyscraper','strong')
el('temple','Temple','🛕','Construction')
re('building','stone','temple','strong')
el('castle_b','Castle','🏰','Construction')
re('stone','king','castle_b','strong')
el('fortress','Fortress','🏰','Construction')
re('castle_b','defense','fortress','strong')
el('palace','Palace','🏛️','Construction')
re('king','building','palace','strong')
el('tower','Tower','🗼','Construction')
re('building','height','tower','strong')
el('lighthouse','Lighthouse','💡','Construction')
re('tower','light','lighthouse','strong')
el('greenhouse','Greenhouse','🏗️','Construction')
re('glass','garden','greenhouse','strong')
el('barn','Barn','🏠','Construction')
re('farm','building','barn','strong')
el('windmill','Windmill','🌬️','Construction')
re('building','wind','windmill','strong')

/* ─── ABSTRACT CONCEPTS ─── */
el('courage','Courage','🦁','Abstract')
re('fear','overcome','courage','strong')
el('hope','Hope','🌟','Abstract')
re('faith','future','hope','strong')
el('destiny','Destiny','🔮','Abstract')
re('time','prediction','destiny','strong')
el('luck','Luck','🍀','Abstract')
re('chance','fortune','luck','strong')
el('chaos','Chaos','🌪️','Abstract')
re('entropy','disorder','chaos','strong')
el('order','Order','📏','Abstract')
re('structure','law','order','strong')
el('balance','Balance','⚖️','Abstract')
re('order','chaos','balance','strong')
el('justice','Justice','⚖️','Society')
re('balance','law','justice','strong')
el('freedom','Freedom','🕊️','Abstract')
re('liberty','choice','freedom','strong')
el('power','Power','💪','Abstract')
re('strength','control','power','strong')
el('progress','Progress','📈','Abstract')
re('innovation','time','progress','strong')
el('curiosity','Curiosity','❓','Abstract')
re('knowledge','wonder','curiosity','strong')

/* ─── FOOD EXTENSIONS ─── */
el('ice_cream','Ice Cream','🍦','Food')
re('cream','ice','ice_cream','strong')
el('cream','Cream','🥛','Food')
re('milk','fat','cream','strong')
el('pasta','Pasta','🍝','Food')
re('dough','shape','pasta','strong')
el('sushi','Sushi','🍣','Food')
re('rice','fish','sushi','strong')
el('burger','Burger','🍔','Food')
re('sandwich','meat','burger','strong')
el('steak','Steak','🥩','Food')
re('meat','fire','steak','strong')
el('smoothie','Smoothie','🥤','Food')
re('fruit','blend','smoothie','strong')

/* ─── FANTASY EXTENSIONS ─── */
el('unicorn','Unicorn','🦄','Fantasy')
re('horse','magic','unicorn','strong')
el('phoenix','Phoenix','🦅','Fantasy')
re('bird','fire','phoenix','strong')
el('mermaid','Mermaid','🧜','Fantasy')
re('human','fish','mermaid','strong')
el('centaur_m','Centaur','🐴','Fantasy')
re('human','horse','centaur_m','strong')
el('griffin','Griffin','🦅','Fantasy')
re('eagle_b','lion','griffin','strong')
el('fairy','Fairy','🧚','Fantasy')
re('magic','small','fairy','strong')
el('elf','Elf','🧝','Fantasy')
re('human','nature','elf','strong')
el('wizard','Wizard','🧙','Fantasy')
re('human','magic','wizard','strong')
el('golem','Golem','🗿','Fantasy')
re('clay','life','golem','strong')
el('vampire','Vampire','🧛','Fantasy')
re('human','bat','vampire','strong')
el('werewolf','Werewolf','🐺','Fantasy')
re('human','wolf','werewolf','strong')

/* ─── GOVERNMENT ─── */
el('democracy','Democracy','🗳️','Society')
re('government','people','democracy','strong')
el('monarchy','Monarchy','👑','Society')
re('government','king','monarchy','strong')
el('senate','Senate','🏛️','Society')
re('government','council','senate','strong')
el('treaty','Treaty','📜','Society')
re('peace','agreement','treaty','strong')

/* ─── WEAPONS ─── */
el('gun','Gun','🔫','Weapons')
re('metal','gunpowder','gun','strong')
el('cannon','Cannon','💣','Weapons')
re('gun','big','cannon','strong')
el('bomb','Bomb','💥','Weapons')
re('explosive','metal','bomb','strong')
el('missile','Missile','🚀','Weapons')
re('rocket','bomb','missile','strong')
el('gunpowder','Gunpowder','💥','Weapons')
re('sulfur','carbon','gunpowder','strong')
el('bow','Bow','🏹','Weapons')
re('wood','string','bow','strong')

/* ─── GEOGRAPHY EXTENSIONS ─── */
el('canyon','Canyon','🏞️','Geography')
re('river','mountain','canyon','strong')
el('fjord','Fjord','🏞️','Geography')
re('glacier','valley','fjord','strong')
el('oasis_geo','Oasis','🏝️','Geography')
re('desert','water','oasis_geo','strong')
el('geyser','Geyser','💨','Geology')
re('water','volcano','geyser','strong')
el('reef','Reef','🪸','Geography')
re('coral','ocean','reef','strong')
el('lagoon','Lagoon','🏝️','Geography')
re('reef','island','lagoon','strong')
el('archipelago','Archipelago','🗺️','Geography')
re('island','island','archipelago','strong')

/* ─── ENVIRONMENT ─── */
re('moon','ocean','tide','strong')
re('ocean','wind','wave','strong')
re('wave','energy','tidal_power','strong')
re('river','dam','hydroelectric','strong')
re('wind','blade','turbine','reasonable')
re('turbine','energy','wind_energy','strong')
re('sun','cell','solar_energy','strong')
re('earth','heat','geothermal','strong')
re('fossil','burn','carbon_dioxide','strong')
re('factory','smoke','pollution','strong')
re('pollution','air','smog','strong')
re('plastic','ocean','microplastic','strong')
re('climate','change','global_warming','strong')
re('global_warming','ice','sea_rise','strong')

/* ─── WEATHER EXTENSIONS ─── */
re('air','water','humidity','strong')
re('cold','humidity','frost','strong')
re('frost','sun','dew','reasonable')
re('storm','ocean','hurricane','strong')
re('sand','wind','sandstorm','strong')
re('lightning','forest','wildfire','strong')
re('ocean','earthquake','tsunami','strong')
re('mountain','snow','avalanche','strong')

/* ─── COMPUTER EXTENSIONS ─── */
re('computer','screen','display','strong')
re('display','touch','touchscreen','strong')
re('computer','camera','webcam','strong')
re('software','music','music_player','strong')
re('video','game','video_game','strong')
re('internet','shop','online_store','strong')