/* ─── ADDITIONAL PROFESSIONS & ROLES ─── */
el('nurse','Nurse','👩‍⚕️','Society')
re('doctor','care','nurse','strong')
el('architect','Architect','👷','Society')
re('engineer','building','architect','strong')
el('librarian','Librarian','📚','Society')
re('teacher','book','librarian','strong')
el('judge','Judge','⚖️','Society')
re('law','court','judge','strong')
el('captain','Captain','⚓','Society')
re('sailor','leader','captain','strong')
el('general','General','⭐','Society')
re('soldier','leader','general','strong')
el('king','King','👑','Society')
re('ruler','crown','king','strong')
el('queen','Queen','👑','Society')
re('king','woman','queen','strong')
el('president','President','🏛️','Society')
re('leader','democracy','president','strong')
el('diplomat','Diplomat','🤝','Society')
re('ambassador','talk','diplomat','strong')

/* ─── SEASONS ─── */
el('spring','Spring','🌸','Weather')
re('flower','season','spring','strong')
el('summer','Summer','☀️','Weather')
re('sun','season','summer','strong')
el('autumn','Autumn','🍂','Weather')
re('tree','season','autumn','strong')
el('winter','Winter','❄️','Weather')
re('snow','season','winter','strong')
el('season','Season','🍂','Weather')
re('year','climate','season','strong')

/* ─── COLORS ─── */
el('red','Red','🔴','Abstract')
re('light','wavelength','red','strong')
el('blue','Blue','🔵','Abstract')
re('light','sky','blue','strong')
el('green','Green','💚','Abstract')
re('plant','light','green','strong')
el('yellow','Yellow','🟡','Abstract')
re('sun','light','yellow','strong')
el('purple','Purple','🟣','Abstract')
re('blue','red','purple','strong')
el('orange_c','Orange','🟠','Abstract')
re('red','yellow','orange_c','strong')
el('rainbow_c','Rainbow','🌈','Weather')
re('light','prism','rainbow_c','strong')

/* ─── INSTRUMENTS MORE ─── */
el('banjo','Banjo','🪕','Culture')
re('guitar','folk','banjo','strong')
el('accordion','Accordion','🪗','Culture')
re('piano','portable','accordion','strong')
el('harmonica','Harmonica','🎶','Culture')
re('flute','small','harmonica','strong')
el('tuba','Tuba','🎺','Culture')
re('trumpet','big','tuba','strong')
el('cello','Cello','🎻','Culture')
re('violin','big','cello','strong')

/* ─── INSECTS ─── */
el('ant','Ant','🐜','Animals')
re('insect','colony','ant','strong')
el('butterfly_i','Butterfly','🦋','Animals')
re('insect','color','butterfly_i','strong')
el('beetle','Beetle','🪲','Animals')
re('insect','shell','beetle','strong')
el('dragonfly','Dragonfly','🪰','Animals')
re('insect','water','dragonfly','strong')
el('firefly','Firefly','🪲','Animals')
re('beetle','light','firefly','strong')
el('grasshopper','Grasshopper','🦗','Animals')
re('insect','jump','grasshopper','strong')
el('cricket','Cricket','🦗','Animals')
re('insect','sound','cricket','strong')
el('scorpion','Scorpion','🦂','Animals')
re('spider','desert','scorpion','strong')
el('mosquito','Mosquito','🦟','Animals')
re('insect','blood','mosquito','strong')

/* ─── SPICES & HERBS ─── */
el('cinnamon','Cinnamon','🟫','Food')
re('bark','spice','cinnamon','strong')
el('pepper_s','Pepper','🌶️','Food')
re('spice','hot','pepper_s','strong')
el('vanilla','Vanilla','🍦','Food')
re('orchid','spice','vanilla','strong')
el('ginger','Ginger','🫚','Food')
re('root','spice','ginger','strong')
el('turmeric','Turmeric','🟡','Food')
re('root','yellow','turmeric','strong')
el('basil','Basil','🌿','Food')
re('herb','green','basil','strong')
el('mint','Mint','🌿','Food')
re('herb','cool','mint','strong')
el('rosemary','Rosemary','🌿','Food')
re('herb','pine','rosemary','strong')

/* ─── SCIENTIFIC FIELDS ─── */
el('biochemistry','Biochemistry','🧪','Science')
re('biology','chemistry','biochemistry','strong')
el('geophysics','Geophysics','🌍','Science')
re('geology','physics','geophysics','strong')
el('astrophysics','Astrophysics','🌌','Science')
re('astronomy','physics','astrophysics','strong')
el('neuroscience','Neuroscience','🧠','Science')
re('biology','brain','neuroscience','strong')
el('ecology','Ecology','🌿','Science')
re('biology','environment','ecology','strong')
el('oceanography','Oceanography','🌊','Science')
re('ocean','science','oceanography','strong')
el('meteorology','Meteorology','🌤️','Science')
re('weather','science','meteorology','strong')
el('paleontology','Paleontology','🦴','Science')
re('fossil','biology','paleontology','strong')

/* ─── GEMS ─── */
el('amber','Amber','🟠','Materials')
re('fossil','tree','amber','strong')
el('pearl','Pearl','📿','Materials')
re('oyster','sand','pearl','strong')
el('opal','Opal','🌈','Materials')
re('gem','rainbow','opal','strong')
el('amethyst','Amethyst','🟣','Materials')
re('crystal','purple','amethyst','strong')
el('topaz','Topaz','🟡','Materials')
re('crystal','yellow','topaz','strong')
el('quartz','Quartz','🤍','Materials')
re('crystal','sand','quartz','strong')
el('marble','Marble','🪨','Materials')
re('stone','pressure','marble','strong')
el('granite','Granite','🪨','Materials')
re('stone','magma','granite','strong')

/* ─── CUISINES ─── */
el('italian_c','Italian','🍝','Food')
re('cuisine','pasta','italian_c','strong')
el('japanese_c','Japanese','🍣','Food')
re('cuisine','rice','japanese_c','strong')
el('mexican_c','Mexican','🌮','Food')
re('cuisine','spice','mexican_c','strong')
el('indian_c','Indian','🍛','Food')
re('cuisine','curry','indian_c','strong')
el('chinese_c','Chinese','🥟','Food')
re('cuisine','noodles','chinese_c','strong')
el('french_c','French','🥖','Food')
re('cuisine','bread','french_c','strong')
el('thai_c','Thai','🍜','Food')
re('cuisine','spice','thai_c','strong')

/* ─── BODIES OF WATER ─── */
el('sea','Sea','🌊','Geography')
re('ocean','large','sea','strong')
el('pond','Pond','🫗','Geography')
re('water','small','pond','strong')
el('waterfall','Waterfall','🌊','Geography')
re('river','cliff','waterfall','strong')
el('glacier','Glacier','🧊','Geography')
re('ice','mountain','glacier','strong')
el('iceberg','Iceberg','🧊','Geography')
re('glacier','ocean','iceberg','strong')
el('beach_g','Beach','🏖️','Geography')
re('sand','ocean','beach_g','strong')

/* ─── EMOTIONS ─── */
el('happiness','Happiness','😊','Abstract')
re('love','joy','happiness','strong')
el('sadness','Sadness','😢','Abstract')
re('loss','emotion','sadness','strong')
el('anger','Anger','😡','Abstract')
re('frustration','emotion','anger','strong')
el('fear_e','Fear','😨','Abstract')
re('danger','survival','fear_e','strong')
el('surprise','Surprise','😮','Abstract')
re('unexpected','event','surprise','strong')

/* ─── DEEP MANUFACTURING ─── */
el('assembly_line','Assembly Line','🏭','Industry')
re('factory','conveyor','assembly_line','strong')
el('mass_production','Mass Production','🏭','Industry')
re('assembly_line','efficiency','mass_production','strong')
el('automation_i','Automation','⚙️','Industry')
re('robot','factory','automation_i','strong')
el('quality_control','Quality Control','✅','Industry')
re('production','inspection','quality_control','strong')
el('supply_chain','Supply Chain','📦','Commerce')
re('factory','transport','supply_chain','strong')
el('logistics','Logistics','📦','Commerce')
re('supply_chain','computer','logistics','strong')

/* ─── RENEWABLE ENERGY ─── */
el('solar_farm','Solar Farm','☀️','Energy')
re('solar_panel','field','solar_farm','strong')
el('wind_farm','Wind Farm','🌬️','Energy')
re('windmill','field','wind_farm','strong')
el('hydro_dam','Hydro Dam','🏗️','Energy')
re('dam','turbine','hydro_dam','strong')
el('geothermal_power','Geothermal Power','🌋','Energy')
re('volcano','turbine','geothermal_power','strong')
el('nuclear_power','Nuclear Power','☢️','Energy')
re('uranium','reactor','nuclear_power','strong')

/* ─── GARDEN/PLANTS MORE ─── */
el('herb_garden','Herb Garden','🌿','Nature')
re('herb','garden','herb_garden','strong')
el('rose_garden','Rose Garden','🌹','Nature')
re('rose','garden','rose_garden','strong')
el('vegetable_garden','Vegetable Garden','🥕','Nature')
re('vegetable','garden','vegetable_garden','strong')
el('orchard','Orchard','🍎','Agriculture')
re('fruit','farm','orchard','strong')
el('vineyard','Vineyard','🍇','Agriculture')
re('grape','farm','vineyard','strong')
el('rice_paddy','Rice Paddy','🌾','Agriculture')
re('rice','water','rice_paddy','strong')