/* ─── SPORTS ─── */
el('soccer','Soccer','⚽','Culture')
re('sport','ball','soccer','strong')
el('basketball','Basketball','🏀','Culture')
re('sport','height','basketball','strong')
el('tennis','Tennis','🎾','Culture')
re('sport','racket','tennis','strong')
el('baseball','Baseball','⚾','Culture')
re('sport','bat','baseball','strong')
el('swimming','Swimming','🏊','Culture')
re('sport','water','swimming','strong')
el('cycling','Cycling','🚴','Culture')
re('bicycle','sport','cycling','strong')
el('skiing','Skiing','⛷️','Culture')
re('sport','snow','skiing','strong')
el('surfing','Surfing','🏄','Culture')
re('sport','wave','surfing','strong')
el('boxing','Boxing','🥊','Culture')
re('sport','fight','boxing','strong')
el('gymnastics','Gymnastics','🤸','Culture')
re('sport','flexibility','gymnastics','strong')
el('yoga','Yoga','🧘','Culture')
re('exercise','meditation','yoga','strong')
el('marathon','Marathon','🏃','Culture')
re('running','distance','marathon','strong')
el('olympics','Olympics','🏅','Culture')
re('sport','competition','olympics','strong')

/* ─── LANDMARKS ─── */
el('pyramid','Pyramid','🔺','History')
re('ancient','stone','pyramid','strong')
el('colosseum','Colosseum','🏛️','History')
re('arena','stone','colosseum','strong')
el('great_wall','Great Wall','🧱','History')
re('wall','stone','great_wall','strong')
el('stonehenge','Stonehenge','🗿','History')
re('stone','ancient','stonehenge','strong')
el('sphinx_hist','Sphinx','🗿','History')
re('lion','human','sphinx_hist','strong')
el('taj_mahal','Taj Mahal','🕌','History')
re('palace','marble','taj_mahal','strong')
el('eiffel_tower','Eiffel Tower','🗼','History')
re('tower','metal','eiffel_tower','strong')
el('statue_liberty','Statue of Liberty','🗽','History')
re('statue','copper','statue_liberty','strong')
el('acropolis','Acropolis','🏛️','History')
re('temple','greece','acropolis','strong')
el('moai','Moai','🗿','History')
re('statue','island','moai','strong')
el('machu_picchu','Machu Picchu','🏛️','History')
re('city','mountain','machu_picchu','strong')

/* ─── FRUITS & VEGETABLES ─── */
el('lemon','Lemon','🍋','Food')
re('citrus','sour','lemon','strong')
el('lime','Lime','🍋','Food')
re('lemon','green','lime','strong')
el('strawberry','Strawberry','🍓','Food')
re('fruit','red','strawberry','strong')
el('blueberry','Blueberry','🫐','Food')
re('fruit','blue','blueberry','strong')
el('watermelon','Watermelon','🍉','Food')
re('fruit','water','watermelon','strong')
el('peach','Peach','🍑','Food')
re('fruit','warm','peach','strong')
el('avocado','Avocado','🥑','Food')
re('fruit','green','avocado','strong')
el('onion','Onion','🧅','Food')
re('vegetable','layer','onion','strong')
el('garlic','Garlic','🧄','Food')
re('onion','pungent','garlic','strong')
el('broccoli','Broccoli','🥦','Food')
re('vegetable','green','broccoli','strong')
el('spinach','Spinach','🥬','Food')
re('vegetable','leaf','spinach','strong')
el('tomato','Tomato','🍅','Food')
re('vegetable','red','tomato','strong')
el('cucumber','Cucumber','🥒','Food')
re('vegetable','water','cucumber','strong')
el('mushroom_f','Mushroom','🍄','Food')
re('fungus','cave','mushroom_f','strong')

/* ─── DRINKS ─── */
el('juice','Juice','🧃','Food')
re('fruit','water','juice','strong')
el('soda','Soda','🥤','Food')
re('water','sugar','soda','strong')
el('milkshake','Milkshake','🥤','Food')
re('milk','ice_cream','milkshake','strong')
el('cocktail','Cocktail','🍸','Food')
re('drink','fruit_juice','cocktail','strong')
el('whiskey','Whiskey','🥃','Food')
re('grain','distill','whiskey','strong')
el('vodka','Vodka','🍸','Food')
re('potato','distill','vodka','strong')
el('rum','Rum','🍹','Food')
re('sugar','distill','rum','strong')

/* ─── DESSERTS ─── */
el('candy','Candy','🍬','Food')
re('sugar','flavor','candy','strong')
el('cookie','Cookie','🍪','Food')
re('dough','chocolate','cookie','strong')
el('donut','Donut','🍩','Food')
re('dough','sugar','donut','strong')
el('pancake','Pancake','🥞','Food')
re('dough','pan','pancake','strong')
el('pudding','Pudding','🍮','Food')
re('milk','sugar','pudding','strong')

/* ─── ANCIENT CIVILIZATIONS ─── */
el('ancient','Ancient','🏛️','History')
re('history','old','ancient','strong')
el('egyptian','Egyptian','🔺','History')
re('ancient','river','egyptian','strong')
el('greek','Greek','🏛️','History')
re('ancient','philosophy','greek','strong')
el('roman','Roman','🏛️','History')
re('ancient','empire','roman','strong')
el('viking','Viking','⛵','History')
re('ancient','norse','viking','strong')
el('medieval','Medieval','🏰','History')
re('history','knight','medieval','strong')
el('industrial_revolution','Industrial Revolution','🏭','History')
re('steam_engine','factory','industrial_revolution','strong')
el('space_age','Space Age','🚀','History')
re('rocket','exploration','space_age','strong')
el('digital_age','Digital Age','💻','History')
re('internet','computer','digital_age','strong')

/* ─── TOOLS EXPANSION ─── */
el('axe','Axe','🪓','Tools')
re('wood','stone','axe','strong')
el('shovel','Shovel','⛏️','Tools')
re('wood','metal','shovel','strong')
el('pickaxe','Pickaxe','⛏️','Tools')
re('stone','metal','pickaxe','strong')
el('chisel','Chisel','🪚','Tools')
re('metal','stone','chisel','strong')
el('saw','Saw','🪚','Tools')
re('metal','tooth','saw','strong')
el('screwdriver','Screwdriver','🪛','Tools')
re('metal','screw','screwdriver','strong')

/* ─── PLANETS ─── */
el('mercury_p','Mercury','🪐','Space')
re('planet','sun','mercury_p','strong')
el('venus_p','Venus','🪐','Space')
re('planet','cloud','venus_p','strong')
el('earth_p','Earth','🌍','Space')
re('planet','life','earth_p','strong')
el('mars_p','Mars','🪐','Space')
re('planet','iron','mars_p','strong')
el('jupiter_p','Jupiter','🪐','Space')
re('planet','gas','jupiter_p','strong')
el('saturn_p','Saturn','🪐','Space')
re('planet','ring','saturn_p','strong')
el('uranus_p','Uranus','🪐','Space')
re('planet','ice','uranus_p','strong')
el('neptune_p','Neptune','🪐','Space')
re('planet','wind','neptune_p','strong')

/* ─── DEEP COMPUTING ─── */
el('database_e','Database','🗄️','Technology')
re('data','computer','database_e','strong')
el('server_c','Server','🖥️','Technology')
re('computer','network','server_c','strong')
el('website','Website','🌐','Technology')
re('internet','software','website','strong')
el('app','App','📱','Technology')
re('smartphone','software','app','strong')
el('social_media','Social Media','📱','Technology')
re('internet','community','social_media','strong')
el('ecommerce','Ecommerce','🛒','Technology')
re('internet','shop','ecommerce','strong')
el('search_engine','Search Engine','🔍','Technology')
re('internet','algorithm','search_engine','strong')

/* ─── MUSIC GENRES ─── */
el('jazz','Jazz','🎷','Culture')
re('music','improvisation','jazz','strong')
el('rock','Rock','🎸','Culture')
re('music','electric','rock','strong')
el('classical','Classical','🎵','Culture')
re('music','orchestra','classical','strong')
el('blues','Blues','🎵','Culture')
re('music','sad','blues','strong')
el('electronic','Electronic','🎹','Culture')
re('music','computer','electronic','strong')
el('hiphop','Hip Hop','🎤','Culture')
re('music','poetry','hiphop','strong')
el('reggae','Reggae','🎵','Culture')
re('music','tropic','reggae','strong')
el('orchestra','Orchestra','🎵','Culture')
re('music','group','orchestra','strong')

/* ─── SEWING/FABRIC ─── */
el('cotton','Cotton','☁️','Materials')
re('plant','fabric','cotton','strong')
el('wool','Wool','🧶','Materials')
re('sheep','fabric','wool','strong')
el('silk_f','Silk','🧵','Materials')
re('worm','fabric','silk_f','strong')
el('leather','Leather','🧤','Materials')
re('skin','fabric','leather','strong')
el('clothing','Clothing','👕','Materials')
re('fabric','needle','clothing','strong')
el('hat','Hat','🧢','Materials')
re('clothing','head','hat','strong')
el('shoes','Shoes','👟','Materials')
re('leather','rubber','shoes','strong')

/* ─── ADDITIONAL CROSS-DOMAIN ─── */
el('paper_airplane','Paper Airplane','✈️','Transport')
re('paper','fold','paper_airplane','strong')
el('kite','Kite','🪁','Culture')
re('paper','wind','kite','strong')
el('balloon','Balloon','🎈','Physics')
re('air','rubber','balloon','strong')
el('soap','Soap','🧼','Materials')
re('oil','base','soap','strong')
el('perfume','Perfume','🧴','Materials')
re('flower','alcohol','perfume','strong')
el('incense','Incense','🪔','Culture')
re('herb','fire','incense','strong')
el('candle','Candle','🕯️','Tools')
re('wax','fire','candle','strong')
el('pottery','Pottery','🏺','Materials')
re('clay','fire','pottery','strong')
el('origami','Origami','🧻','Culture')
re('paper','fold','origami','strong')
el('clock_tower','Clock Tower','🕐','Construction')
re('clock','building','clock_tower','strong')
el('wind_chime','Wind Chime','🎐','Culture')
re('metal','wind','wind_chime','strong')
el('mirror','Mirror','🪞','Tools')
re('glass','silver','mirror','strong')
el('telescope_g','Telescope','🔭','Tools')
re('lens','tube','telescope_g','strong')
el('microscope_g','Microscope','🔬','Tools')
re('lens','magnify','microscope_g','strong')
el('telescope','Telescope','🔭','Tools')
re('lens','star','telescope','strong')

/* ─── EXTRA CROSS-RECIPES ─── */
re('stone','saw','brick','reasonable')
re('clay','tool','pottery','strong')
re('wood','tool','furniture','strong')
re('wood','metal','weapon','strong')
re('stone','metal','tool','strong')
re('wool','knitting','sweater','strong')
re('sweater','warm','comfort','reasonable')
re('wheat','scythe','harvest','strong')
re('grape','press','juice','strong')
re('apple','press','juice','strong')
re('wind','sail','ship','strong')
re('steam','locomotive','train','strong')
re('electricity','light','street','strong')
re('sun','heat','solar_heater','strong')
re('solar_heater','water','hot_water','strong')
re('engine','propeller','airplane','strong')
re('robot','intelligence','smart_robot','strong')
re('smart_robot','human','android','strong')
re('space','explore','space_exploration','strong')
re('space_exploration','rocket','moon','strong')
re('moon','base','lunar_base','strong')
re('lunar_base','city','moon_city','strong')
re('water','electrolysis','hydrogen','strong')
re('hydrogen','fuel','clean_energy','strong')
re('nuclear','fusion','fusion_power','strong')
re('fusion_power','city','clean_city','strong')
re('science','future','futurology','strong')
re('futurology','ai','transhumanism','reasonable')